### ISSUE TITLE
Increase backing and approval timeouts for async backing

### ISSUE THREAD

**Issue by Sophia-Gold** [paritytech/polkadot-sdk#1366]
Since async backing increases execution time for collators from 500ms to 2s, we should also increase the execution time for backers and approval checkers beyond 2s to avoid larger parachain blocks not being backed due to small resource differences, nondeterminism, or cache misses. 

The question is by how much. It's unclear whether we need to retain the 4x difference as 8s is quite long. This warrants testing.

**Comment by burdges** [comment]
We'd ideally pseudo-remove the gap between backer timeouts and approval checker timesout once we charge backers fr time overruns: https://github.com/paritytech/polkadot-sdk/issues/742

In practice there is inherently some gap where the backer earns something for oversized blocks, but in expectation they risk only a minor fee for the time overrun.  We discussed the fee curve shape at the team retreat.  I'd suggested time overrun fees should be curve fit to the costs of no shows, but you maybe had something more nuanced, or just different.

At present I've no thoughts on doing something different short-term, but yeah maybe a hacky setting makes sense if we want to deploy something faster.

**Comment by rphmeier** [comment]
In my opinion we should start from the amount of work backers should do and work backwards to what collators should use as a timeout.

**Comment by burdges** [comment]
I doubt "timeout" is even well defined for collators.  An optimized collator would often run quite different code from validiator.

We're worried about the gap between backers vs approval checkers here.  Alfonso proposed a 6x gap in https://github.com/paritytech/polkadot/pull/1656  We never used his 6x but we ended up with at least the 4x gap @Sophia-Gold mentions.  In fact I thought we're currently running some larger gap, like 6x or 8x.

We'll pseduo-remove the gap in https://github.com/paritytech/polkadot-sdk/issues/742 like I say, but tight now the question is:  Can we deploy async backing without https://github.com/paritytech/polkadot-sdk/issues/742 but with a smaller gap.

I've now forgotten how the developers selected such a large gap, so we'll just need to ask whoever put the gap into the code where it came from, and try to reason from that point.

**Comment by rphmeier** [comment]
We should really separate these concerns and be clear about what we're discussing

1. how much different does the backing timeout vs. the approval/disputes timeout need to be in execution? currently, backing has a 2s timeout and disputes/approval have a 12s timeout. This is in line with Alfonso's recommendation.
2. how much time collators allocate to block building in order to stay within the 2s timeout on backers.

This issue was mostly made in the context of (2). We previously had limitations on block building in Cumulus by default which were 0.5s of authoring. However, this timeout was not set with the goal of fulfilling (2) and was majority constrained by other factors. With async backing (2) becomes a direct concern. That's all.

> Is this really the only reason we have the 4x gap?

It's the only reason we have 4x gap between the 0.5s allocated to collators block building and the 2s backing timeout, yes. Building, backing, and propagating within a 6s window required a very short block-building timeout mostly due to network and relay chain block propagation overhead.

This is not related to the 6x gap between the 2s allocated to backing and the 12s allocated to approval, as mentioned.

**Comment by eskimor** [comment]
So, I guess we can close this then. We might end up wanting to increase backing timeout slightly to something like 2.5s at some point, but for now we should be good.
