### ISSUE TITLE
Adjust `GenesisBuilder` naming

### ISSUE THREAD

**Issue by michalkucharczyk** [paritytech/polkadot-sdk#150]
`GenesisBuilder` trait needs some naming adjustments.

              LGTM other than a grumble about naming which I hope to see fixed before this is stabilized.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/14310#pullrequestreview-1541606306_

Refer also to: https://github.com/paritytech/substrate/pull/14131#pullrequestreview-1435453355

part of: https://github.com/paritytech/polkadot-sdk/issues/25

**Comment by kianenigma** [comment]
To re-iterate, I have two points: 

1. We are using the word "config", where it is meant to just represent "state". For example `fn build_config(config: Vec<u8>, param: Vec<u8>) -> sp_genesis_builder::Result` which is now part of all runtimes is doing _nothing_ other than building the initial "state". Why are we calling this "config"? there is no "configuration" involved. 
2. And, the former point is important, because is FRAME `Config` means something specific, and I worried that people would mix the two.

**Comment by JoshOrndorff** [comment]
This is relevant to what we are doing in https://github.com/Off-Narrative-Labs/Tuxedo/pull/127 (cc @muraca) and my question at https://substrate.stackexchange.com/questions/10105/extrinsics-in-genesis-block

IDK if it is in scope for this issue, but we are wanting to allow chain launchers to specify genesis transactions (yes transactions, not just state) in their chain specs. But have so far relied on a storage hack.

**Comment by michalkucharczyk** [comment]
This issue is only about re-naming the components that are already in place (e.g : [`GenesisBuilder API`](https://github.com/paritytech/polkadot-sdk/blob/3e980219862d58aa52fd0b4dfff907d69ce92790/substrate/primitives/genesis-builder/src/lib.rs#L38), which were implemented to add support for `GenesisConfig` in wasm runtimes. (refer to: https://github.com/paritytech/polkadot-sdk/issues/25). 

Adding support for genesis extrinsic is definitely out of scope of this ticket.

**Comment by bkchr** [comment]
> IDK if it is in scope for this issue, but we are wanting to allow chain launchers to specify genesis transactions (yes transactions, not just state) in their chain specs. But have so far relied on a storage hack.

This is already supported, as I have answered you on SE.

**Comment by michalkucharczyk** [comment]
New naming proposed in https://github.com/paritytech/polkadot-sdk/pull/2714 (cc: @kianenigma)

**Comment by jhoyosp** [comment]
## Update: Debug Logs Analysis (December 25, 2025)

After enabling debug logging (`RUST_LOG=info,parachain=debug,aura=debug,cumulus-collator=debug`), we found the **root cause**:

### Critical Finding

```log
DEBUG parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=0 failed_to_resolve=0
DEBUG parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=0 removed=0
```

**The collator requests 0 validators because it doesn't see any core assignment.**

### What the logs show:
- ✅ Relay chain synced (9+ peers, importing blocks)
- ✅ Slot calculations working (`Adjusted relay-chain slot to parachain slot`)
- ❌ **NO "claim slot" attempts**
- ❌ **NO "Starting collation" messages**
- ❌ **NO "Building block" attempts**
- ❌ **0 validators requested for connection**

### Expected vs Actual Behavior

**Expected** (from working parachains):
```log
DEBUG cumulus-collator: Starting collation for relay parent
DEBUG aura: Claiming slot N
DEBUG sc_basic_authorship: Prepared block proposal
INFO Produced block
```

**Actual**:
```log
DEBUG aura::cumulus: Adjusted relay-chain slot to parachain slot...
(silence - no collation attempts)
```

### Hypothesis

The lookahead collator queries the relay chain for the **claim queue** to determine if it should produce a block. Even though:
- Core 42 is assigned to Task 5080 (verified by Paseo support)
- The workplan was committed to the relay chain

The collator is not finding this assignment in its claim queue query.

### Questions for the team:

1. How does the lookahead collator determine it has a core assignment?
2. Is there a specific RPC or runtime API the collator uses to check this?
3. Could there be a mismatch between "Parathread" lifecycle and bulk coretime expectations?

Current para lifecycle: `paras.paraLifecycles(5080) = Parathread (0x01)`
