### ISSUE TITLE
Add destination info in FeeManager::handle_fee

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#1549]
In https://github.com/paritytech/polkadot-sdk/pull/1234, `XcmFeesToAccount` was added, which puts the delivery fees in a specified account.

A comment was raised about the benefit of putting the fees on different accounts based on the destination of the transport protocol.
However, this needs a change in the `FeeManager` API.
Right now `FeeManager::handle_fee` doesn't take in the destination, and it should to make this possible.

Something like this:

```rust
fn handle_fee(fee: MultiAssets, context: Option<&XcmContext>, destination: Option<&MultiLocation>);
```

**Comment by KiChjang** [comment]
The original comment is really looking for the ID of the bridge that is going to be used to send XCMs over. Given that's the case, instead of modifying the function signature, we could simply pass in the bridge ID as part of the XcmContext -- I imagine that the ID would be useful in other situations as well.

**Comment by serban300** [comment]
Not sure if possible (didn't try it), but another option that comes to mind would be to modify `handle_fee()` in order to provide the fee reason. Something like this:

```
fn handle_fee(fee: MultiAssets, context: Option<&XcmContext>, reason: FeeReason);
```

And add the destination to the `FeeReason` variants where it makes sense (for example to `FeeReason::TransferReserveAsset`, etc )

Seems a bit more specific then passing the bridge id or destination all the time. And maybe could be useful for other scenarios unrelated to the bridge.

**Comment by KiChjang** [comment]
@serban300 I thought of that too, but in that case, you're just duplicating code for a specific use-case. I would like the solution to be more general than that, hence I suggested putting it into `XcmContext` altogether.

**Comment by serban300** [comment]
@KiChjang Not sure if we would need to duplicate code for this. But you might be right. I didn't think of that.

@franciscoaguirre Could I help with this issue ? I would be happy to tackle it if you don't have time. Since we also need it for the bridges.

**Comment by serban300** [comment]
Published https://github.com/paritytech/polkadot-sdk/pull/2021 for this.

@KiChjang in the end I added the `FeeReason` to `handle_fee()` since we needed it in order to add separate logic only for `ExportMessage` and I think in general it should offer more flexibility regarding fee handling. And there was no need for code duplication. But if you have strong preferences towards adding the network ID in the context, please let me know.

**Comment by serban300** [comment]
Resolved in by https://github.com/paritytech/polkadot-sdk/pull/2021
