### ISSUE TITLE
Backers retry on failed candidate validation

### ISSUE THREAD

**Issue by Overkillus** [paritytech/polkadot-sdk#1585]
Loosely connected to https://github.com/paritytech/polkadot-sdk/issues/1434 where the potential issue was first recognised.

Backers seem to retry failed validation (once per error type). In general it would be better to have backing stricter than approval voting / disputes. This is currently the case for timeouts but another aspect should be respecting transient errors and not doing any retries in in the backing stage. This reduces the chance of nondeterministic blocks getting backed and honest backers getting slashed.

Call path in question:
`polkadot-sdk/polkadot/node/core/backing/src/lib.rs` always delegates backing validation to `fn request_candidate_validation` which in turn send a message `CandidateValidationMessage::ValidateFromExhaustive`. This particular message triggers a `fn validate_candidate_exhaustive` which leads directly to `fn validate_candidate_with_retry`. Backing uses the validation implementation with a retry instead of the `fn validate_candidate`.

`fn validate_candidate_with_retry` allows the validation to be retried in cases of:
- completely invalid candidate
- ambiguous worker death
- internal error

Each case can be retried once. So it is possible that multiple retires will be attempted.

This can be somewhat easily amended by passing extra details in the message and changing the behaviour in candidate validation in case of backing validation. The new behaviour will simply refer to the non retry version of the func.

**Comment by Overkillus** [comment]
@eskimor if you could take a look if we want to go with it

**Comment by burdges** [comment]
Is there any reason backers should retry under any circumstances?  I'd think they could just report the error and move on, either the operator or the parachain can then fix the error.

**Comment by burdges** [comment]
Invalid candidates maybe interesting if we want the backer to post a dispute, but this could be handled by making those backers act like normal approval checkers on candidates which they failed the first time.  I doubt this matters either way honestly since it's a negligible number of nodes.

**Comment by s0me0ne-unkn0wn** [comment]
"Can be easily amended" does not work well with "passing extra details in the message" :sweat_smile: Adding a new field to the validation message is a rather big pain in the ass. See #1190 for an example, ~90% of code in that PR is about adding a field and fixing all the tests (that entire approach requires some refactoring for sure, but definitely not in the scope of this issue).

But indeed I believe you don't need a new field. The `ValidateCandidateFromExhaustive` has the `PvfExecTimeoutKind` field, it's either `Backing` or `Approval`, so you can find out what job is supposed to be done. Yes, it looks like a misuse of the field, but I believe it's better to, say, rename `PvfExecTimeoutKind` into something more general than to introduce a new one.

**Comment by Overkillus** [comment]
> "Can be easily amended" does not work well with "passing extra details in the message" 😅

Didn't realise it would be such a hassle.

> But indeed I believe you don't need a new field. The ValidateCandidateFromExhaustive has the PvfExecTimeoutKind field, it's either Backing or Approval

I've seen the timeout field but didn't want to go this route as it didn't seem particularly clean. Maybe renaming that is inded a good middle-ground 👍

**Comment by eskimor** [comment]
Renaming and making it more general purpose should be the way to go. Separation of concerns should be maintained. So instead of telling candidate validation that we want this validation for backing/approval/dispute/... we should tell it:

Do the validation with this timeout, this priority and don't do any retries.

**Comment by mrcnski** [comment]
Makes total sense. This could also decrease system pressure on backers in cases where they are overloaded, i.e. getting a lot of processes hit by OOM. 

I just wonder if we could continue retrying on errors we are 100% sure are local ([here's](https://github.com/paritytech/polkadot-sdk/blob/f84b89710b/polkadot/node/core/pvf/common/src/error.rs#L122) the list). The indeterminism in this case has nothing to do with the candidate, but with the local machine, so it seems fair to give it another shake. In practice it shouldn't make much difference, since others in the backing group can cover us, but I also don't see why not do it... Well... connecting with what I said in the first paragraph, I guess the most likely reason for a local error is due to system pressure, and then retrying could add load and make things worse. So yeah, let's go with no retries.

@Jpserrat interested in taking this one?

**Comment by Jpserrat** [comment]
Hey @mrcnski, I'm going to start first thing tomorrow, thanks!

**Comment by burdges** [comment]
We should avoid triggering disputes for local errors, but backers never trigger disputes anyways.  Although not 100% clear, it's likely fine if backers do not retry even on local errors.  We'll need the retry code for approval checkers though too, but yeah I think no retries sounds just fine.

We cannot be 100% sure errors are local because vulnerabilities could sneak into strange places.  Another reasons..
