### ISSUE TITLE
Disallow usage of `from_ref_time` for weights after the relevant polkadot version

### ISSUE THREAD

**Issue by Chralt98** [paritytech/polkadot-sdk#1589]
Hey valuable Polkadot community,

we were able to construct a runtime with `from_ref_time` [here](https://github.com/zeitgeistpm/zeitgeist/blob/bb0e6716cc3fb56d8248e206bfa00f3661a60245/runtime/common/src/weights/pallet_preimage.rs#L81), although weights-v2 are active by our used polkadot version. This resulted in transactions not being able to be processed by the nodes. If a transaction doesn't use `from_ref_time` we were able to execute those transactions.

Could you please deprecate the usage of `from_ref_time` so that everyone sees that this function shouldn't be called anymore by the specific polkadot version?

**Comment by ggwpez** [comment]
>This resulted in transactions not being able to be processed by the nodes. If a transaction doesn't use from_ref_time we were able to execute those transactions.

I dont follow this logic. `from_ref_time(x)` is exactly equivalent to `from_parts(x, 0)`, it was just a convenience wrapper.  

Anyhow, it was removed in https://github.com/paritytech/substrate/issues/13475 already.

**Comment by ggwpez** [comment]
I just queried `System::blockWeight` and it reports about this:  
```pre
  normal: {
    refTime: 0
    proofSize: 0
  }
  operational: {
    refTime: 0
    proofSize: 0
  }
  mandatory: {
    refTime: 7,348,715,184
    proofSize: 69,273,040
  }
}
```
Which means that some `on_initialize` or `on_finalize` calls are consuming about 70 MB of pov size, while your limit is (correctly) set to 5 MiB.  
So that could be why only transactions that have `from_ref_time` in them are being processed.  

It looks like there is a sudo key set, so you can try `Sudo(Utility::WithWeight(SetCode(...), (0, 0))` to force a transaction in.  
I think there is currently no PoV base weight per transaction, so could be that this works. But better test with a `Remark` first.

**Comment by ggwpez** [comment]
Yes pretty much confimed. PRediction market on_init is using about 70 MB proof per block as introduced here: https://github.com/zeitgeistpm/zeitgeist/commit/bb0e6716cc3fb56d8248e206bfa00f3661a60245#r127466669  

We are adding some sanity checker for parachains here https://github.com/paritytech/polkadot-sdk/pull/1493, but currently the mandatory weight needs to be checked manually or by using something like subweight: https://github.com/ggwpez/substrate-weight-compare
