### ISSUE TITLE
Cleanup Westend & Rococo Gov V1 storage

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#1618]
@liamaharon @al3mart could this cleanup be done in a separate PR? 
we really need this to be merged asap :) 

Thanks!

_Originally posted by @mordamax in https://github.com/paritytech/polkadot-sdk/issues/1177#issuecomment-1723469221_
            
---

Westend/Rococo Gov V1 storage is removed. Need to clean up the storage. See https://github.com/paritytech/polkadot/pull/7314 for how this was done for Kusama & Polkadot.

**Comment by eagr** [comment]
I wanna help out if it's ok.

I presume the cleanup will be done by migrations, right? I could get a rough idea of how to do migrations from https://github.com/paritytech/polkadot/pull/7314, but I'm not sure how to determine what exactly should be removed or unreserved?

**Comment by al3mart** [comment]
I have made a dry run of the migrations and the values I got are the following

| Module | Total Accounts | Total stake to unlock | Total deposit to unreserve |
| ------- | --------------- | --------------------- | -------------------------- |
| Elections Phragmen | 27 | 1,132.821063320441 ROC | 1.465386531600 ROC |
| Democracy | 69 | 2733.923509345613 ROC | 0.166666665000 ROC |
| Tips | 4 | N/A | 0.015099999849 ROC |

The migrations will also remove the following amount of keys

103 Democracy keys 🧹
5 Council keys 🧹
1 TechnicalCommittee keys 🧹
25 PhragmenElection keys 🧹
1 TechnicalMembership keys 🧹
9 Tips keys 🧹

During the dry-run I have noticed the following output
```
Logic error: Unexpected underflow in reducing consumer
```

I understand that means that there are some accounts that haven't been reaped before because of these pallets. The total # of accounts in this situation is **37** (at least that message was logged 37 times). Should we address these in any way ?

**Comment by liamaharon** [comment]
> I understand that means that there are some accounts that haven't been reaped before because of these pallets. The total # of accounts in this situation is 37 (at least that message was logged 37 times). Should we address these in any way ?

Yeah this is expected and is benign/can be ignored.

Thanks for handling it :)
