### ISSUE TITLE
rpc_methods did not include rpc_methods 

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1627]
Previous issue: https://github.com/paritytech/substrate/issues/11728

**Comment by bkchr** [comment]
Please move to: https://github.com/paritytech/json-rpc-interface-spec/

**Comment by xlc** [comment]
I don't think we need to modify spec https://paritytech.github.io/json-rpc-interface-spec/api/rpc_methods.html
It is the implementation here is wrong.

**Comment by bkchr** [comment]
I more meant to document that `rpc_methods` should include `rpc_methods` as well. The new api is currently implemented one after another.

**Comment by bkchr** [comment]
CC @lexnv

**Comment by lexnv** [comment]
Indeed the jsonrpsee exposes the [available methods](https://github.com/paritytech/jsonrpsee/blob/96c035c56094606fe98b98f9a033cced32781d04/core/src/server/rpc_module.rs#L396) registered (yet).

Substrate calls this method before registering the `rpc_methods`, because the result must be captured by the closure:
https://github.com/paritytech/polkadot-sdk/blob/bc5005217a8c2e7c95b9011c96d7e619879b1200/substrate/client/rpc-servers/src/lib.rs#L147-L156

Will create a patch for this, thanks for reporting!
