### ISSUE TITLE
Internal scan of rfc6598 using --no-private-ipv4

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1721]
Original issue https://github.com/paritytech/substrate/issues/9922

This happened to one of our collator node.

[is_global](https://docs.rs/ip_network/latest/ip_network/struct.Ipv4Network.html#method.is_global) is including `Shared Address Space (100.64.0.0/10)` which causes the problem.

We need to either have a generalized way to specify the ranges to block, or have another flag to block shared address space, or explicitly block it when `no-private-ipv4` is enabled

**Comment by altonen** [comment]
We could introduce another flag `--only-global-ipv4` as suggested [here](https://github.com/paritytech/substrate/pull/4042#issuecomment-551034195) which filters out a whole bunch of [addresses](https://docs.rs/ip_network/latest/ip_network/struct.Ipv4Network.html#method.is_global). That seems more natural than patching `--no-private-ipv4` to include Shared Address Space

**Comment by dmitry-markin** [comment]
That's interesting, because the [docs](https://docs.rs/ip_network/latest/ip_network/struct.Ipv4Network.html#method.is_global) and [sources](https://github.com/JakubOnderka/ip_network/blob/950fe3ef43a348a59605fac8a98b1aa7c19791d2/src/ipv4_network.rs#L580-L597) of `ip_network::Ipv4Network::is_global` clearly say that the Shared Address Space (`100.64.0.0/10`) is not considered global. And we already use [`IpNetwork::is_global`](https://github.com/JakubOnderka/ip_network/blob/950fe3ef43a348a59605fac8a98b1aa7c19791d2/src/ip_network.rs#L176-L182) which uses [`Ipv4Network::is_global`](https://github.com/JakubOnderka/ip_network/blob/950fe3ef43a348a59605fac8a98b1aa7c19791d2/src/ipv4_network.rs#L580-L597) internally for IPv4 addresses when `--no-private-ipv4` is specified: https://github.com/paritytech/polkadot-sdk/blob/de71fecc4e58d99474ff655789801e5edf3764b1/substrate/client/network/src/discovery.rs#L580

What exactly is the problem with the collator node? Should the IPv4 shared address space be included or excluded from the connection attempts? Becasue right now `--no-private-ipv4` flag behaves exactly as the proposed `--only-global-ipv4`.

**Comment by xlc** [comment]
yeah I read the docs wrong. Right now it should work. Let me double check the logs and service provider.
