### ISSUE TITLE
Ideas for a new set of example/template pallets

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#186]
good start, although I hope we can also revise both this and `example/ basic` in a more fundamental manner -- I think a lot of the existing features that are put into these example pallets are somewhat nonsensical and could be improved.

```[tasklist]
### I can imagine set of 4 example pallets:
- [x] 1. `template`: a shell pallet, it is your starting point.
- [x] 2. `basic`: one that has a small set of features, akin to a smart contract
- [x] 3. `kitchensink`: one that has ALL of the features. https://github.com/paritytech/substrate/pull/14052
- [x] 4. `dev-mode`: meant to demonstrate the difference between the latter and `dev-mode`.
```

As for nodes 

```[tasklist]
- [x] `node-manual-seal` template
- [x] `node-fast-block` template
- [x] `node-grandpa-aura` template
```

I can actually work on this myself as a part of doc-revamp.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/13944#pullrequestreview-1391416198_

**Comment by liamaharon** [comment]
> 1. template: a shell pallet, it is your starting point.

This is already implemented here: `substrate/bin/node-template/pallets/template/src/lib.rs`. I'm unsure why it's seperate from the rest of the example pallets, maybe it should be moved there?

---

Do we really need both a 'basic' pallet and a 'kitchensink' pallet? 
- I understand the kitchensink would be very close to the basic one, but just with a few extra features
- I'm not sure when as a developer I'd want to reach for 'basic' rather than 'kitchensink', since I'd be using it as a template / example to write my own pallet from it makes sense to just have all the features I might want on-hand
- Having both pallets is additional complexity for developers (need to decide which to reach for) and additional maintenance burden on the FRAME team
- I feel it will be difficult to differentiate between what should be in the 'basic' and what should be in the 'kitchensink'.

---

'template' and 'basic' have similar meanings, I could imagine people being confused about the difference just from looking at the names. Maybe a more descriptive name for the template pallet could be 'starter' or 'skeleton'?

**Comment by sam0x17** [comment]
> I'm unsure why it's seperate from the rest of the example pallets

Side note / random nit: I would really like to see all the frame examples in a proper/real "examples" directory for the `frame` crate, when that comes into existence, since cargo has a facility built in for examples and we are essentially dodging it with our current structure by virtue of `frame` not being a real crate.

**Comment by AlexD10S** [comment]
Trying to get a solution into this StackExchange Question: [How to customize pallet_contracts?](https://substrate.stackexchange.com/questions/9788/how-to-customize-pallet-contracts) I found this very old tutorial  by Shawn: [Extending Substrate Runtime Modules](https://www.shawntabrizi.com/substrate/extending-substrate-runtime-modules/) where it shows how to create a pallet that wraps the `pallet_contracts` adding some functionality.

I believe it makes sense to add an example of  a “wrapper pallet” which adds some functionality on top of an existing pallet (`basic_pallet` for example).
