### ISSUE TITLE
disabling: persist disabled state within one era

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot-sdk#1966]
Currently, we clear out disabled validators in the session pallet on session boundaries. This makes attack on session boundaries easier while avoiding being disabled. We can even consider persisting disabled state to one next era if the validator is chosen again. Note: this might require tracking key rotations properly.

**Comment by Overkillus** [comment]
I agree that we want disabling to last 1 era but this is in fact already the case!

Technically from the perspective of a session pallet disabled validators are [cleared](https://github.com/paritytech/polkadot-sdk/blob/92e142555d45f97aa88d241665d9952d12f4ae40/substrate/frame/session/src/lib.rs#L507-L514) when it ends. But the staking pallet that hosts the session pallet actually repopulates the disabled list on a new session start [here](https://github.com/paritytech/polkadot-sdk/blob/d733c77ee2d2e8e2d5205c552a5efb2e5b5242c8/substrate/frame/staking/src/pallet/impls.rs#L471). This should persist the disabled list for the whole era if I'm reading everything correctly.

This intention is also reflected in the original [PR](https://github.com/paritytech/substrate/pull/9448/files) for an old [issue staking: only disable slashed validators and keep them disabled for whole era](https://github.com/paritytech/substrate/pull/9448). Explicitly the behaviour we wanted supposedly already implemented 😃 

https://github.com/paritytech/polkadot-sdk/pull/2226 is not needed to enable this behaviour and we can close the issue.

**Comment by Overkillus** [comment]
For clarity. This behaviour was already present even before https://github.com/paritytech/polkadot-sdk/pull/2226 got merged. Disabling was lasting for a full era with when the staking pallet is present. A false assumption was made that disabling lasted for a session (4h) instead of an era (24h) because the session pallet clears the disabled validators list every session. When the staking pallet is present it repopulates the session's disabled validator list until the era changes effectively making them last for a full era.
