### ISSUE TITLE
`bandersnatch_vrfs` can cause dependency mess up

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#2013]
We can currently not enable the `std` feature of the `bandersnatch_vrfs` dependency of `sp-core` [here](https://github.com/paritytech/polkadot-sdk/blob/f3bf5c1acdccf953774ee055a8a0465e1e2a3475/substrate/primitives/core/Cargo.toml#L78).  

If i add it, then it cannot build `sp-runtime-interface` anymore. The last time i tried it was a different build error about a duplicate crate.  
```pre
$ cargo c -p sp-runtime-interface

error: no matching package named `sp-ark-bls12-381` found
location searched: https://github.com/paritytech/ark-substrate
required by package `sp-bls12-381 v0.4.1-beta (https://github.com/paritytech/substrate-curves#60c204f3)`
    ... which satisfies git dependency `sp-bls12-381` of package `bandersnatch_vrfs v0.0.1 (https://github.com/w3f/ring-vrf?rev=4b09416#4b09416f)`
    ... which satisfies git dependency `bandersnatch_vrfs` (locked to 0.0.1) of package `sp-core v21.0.0 (/media/vados/980Pro/work/polkadot-sdk/substrate/primitives/core)`
    ... which satisfies path dependency `sp-core` (locked to 21.0.0) of package `asset-hub-kusama-runtime v0.9.420 (/media/vados/980Pro/work/polkadot-sdk/cumulus/parachains/runtimes/assets/asset-hub-kusama)`
    ... which satisfies path dependency `asset-hub-kusama-runtime` (locked to 0.9.420) of package `integration-tests-common v1.0.0 (/media/vados/980Pro/work/polkadot-sdk/cumulus/parachains/integration-tests/emulated/common)`
    ... which satisfies path dependency `integration-tests-common` (locked to 1.0.0) of package `asset-hub-rococo-integration-tests v1.0.0 (/media/vados/980Pro/work/polkadot-sdk/cumulus/parachains/integration-tests/emulated/assets/asset-hub-rococo)`
```

I think it would help if the `bandersnatch_vrfs` was pushed to crates-io instead of using git. Also AFAIK there is a cyclic dependency between `bandersnatch`  and `sp-core`.  
Currently Zepter is configured to [ignore](https://github.com/paritytech/polkadot-sdk/blob/4a44356773d27221c4ac9e48786d07dc72104a48/.config/zepter.yaml#L19) this. Does not seem to be a big problem - just opening this ticket so we dont forget it.

**Comment by davxy** [comment]
@ggwpez Ty for reporting

The issue here is the following dependency chain:

```
sp-core (substrate) -> bandersnatch_vrfs (external) -> sp-ark-ed-on-bls12-381-bandersnatch (external) -> sp-crypto-ec-utils (substrate)
```

That is, in the end `bandersnatch_vrfs` depends on a crate which uses a Substrate dependency to opt-in some optimizations.

This is the error that I get  
```
$ cargo check -p sp-runtime-interface
error: There are multiple `sp-runtime-interface` packages in your project, and the specification `sp-runtime-interface` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  file:///mnt/ssd/develop/parity/polkadot-sdk/substrate/primitives/runtime-interface#sp-runtime-interface@17.0.0
  https://github.com/paritytech/polkadot-sdk#sp-runtime-interface@17.0.0
```

This is due to the fact that there are two `sp-runtime-interface` references:
- the one "by path" used by crates internal to `polkadot-sdk` repo.
- the one "by url" used by (a dependency of) `bandersnatch_vrfs` crate. 

I'm working to find a clean solution... and apparently looks like maybe we'll require to embed bandersnatch vrf code (which is quite lightweight) in sp-core bandersnatch crate. As I said... in the end are just few lines of added code. The real meat is in `dleq_vrf` and `ring_proof`.

cc @burdges

**Comment by burdges** [comment]
oh wow really?  I'd thought we avoided having to do this, thanks to the dependency injection in ark-substrate.  If necessary then alright.

**Comment by burdges** [comment]
We should add a `not(std)` in https://github.com/w3f/ring-vrf/blob/master/bandersnatch_vrfs/src/lib.rs#L24C34-L24C34 so that `bandersnatch_vrfs` does not build if one enables both substrate-curves and std together.   Any objections?

We'll then still have a build error here, but it'll point the way to the correct fix: Not enabling substrate-curves in the host.

**Comment by davxy** [comment]
@alvicsam is this expected?

Please refer to my comment here https://github.com/paritytech/polkadot-sdk/issues/2013#issuecomment-1777756907

In short: is expected the CI job (iirc `cargo-check-each-crate`) to fail if a substrate crate depends on a crate which itself depends on another substrate crate?
**NOTE**: Not the same substrate crate... no circular dependencies.
In this case is `sp-core -> [external] -> sp-runtime-interface`

**Comment by bkchr** [comment]
The bigger problem here is still the inclusion of `sp-runtime-interface` in two ways. Cargo will see them as two different crates that will mean that the traits are not compatible etc. The proper solution to this is that we are based on the crates.io release and that we don't bump the major version all the time, because then crates are again "incompatible" to each other.

We can probably put a band aid fix for this CI check, but this will not solve the underlying problem.

**Comment by kayabaNerve** [comment]
Not to say this hasn't been thought through, yet as someone who doesn't have the reasoning apparent, why not merge arkworks-substrate into the monorepo under substrate itself? I looked through the old substrate repo, the above PR, and the external repo's README/Initial commit to try and find this context. Apologies if I missed it.

**Comment by ggwpez** [comment]
>We can probably put a band aid fix for this CI check, but this will not solve the underlying problem.

The current band-aid is to not enable the `bandersnatch_vrfs/std` feature that causes this and telling Zepter to [ignore it](https://github.com/paritytech/polkadot-sdk/blob/4a44356773d27221c4ac9e48786d07dc72104a48/.config/zepter.yaml#L19).  
I dont think that we should disable the `cargo-check-each-crate`, since it is working as intended.

**Comment by davxy** [comment]
BTW the ugly thing is that we end up with duplicates of our own crates in the `Cargo.lock`.

**Comment by burdges** [comment]
> The bigger problem here is still the inclusion of sp-runtime-interface in two ways.

Is this because we need different features in the host and runtime?  That must surely be common place.

**Comment by bkchr** [comment]
> In short: is expected the CI job (iirc `cargo-check-each-crate`) to fail if a substrate crate depends on a crate which itself depends on another substrate crate?

https://github.com/paritytech/polkadot-sdk/pull/2098 this should fix it.
