### ISSUE TITLE
Broken Staking `try-state` invariants on Westend

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#2020]
- [x] `Staking` has failing storage invariant: `"NotController"` (Edit: _fixed_)
- [x] `FastUnstake` has failing storage invariant: `"the value of ErasToCheckPerBlock is greater than T::MaxErasToCheckPerBlock"` (Edit: _fixed_)
- [x] `NominationPools` has lots of ED warnings (Edit: _fix is in the next runtime upgrade_)
  - Same issue as https://github.com/paritytech/polkadot-sdk/issues/158
- [ ] `VoterList` takes forever to run, get stuck here https://github.com/paritytech/polkadot-sdk/blob/ff3a3bca449a3cae910d2dc8c7ed3658938c6478/substrate/frame/bags-list/src/list/mod.rs#L554-L558

## Steps to reproduce

1. Install `try-runtime-cli`
```bash
cargo install --git https://github.com/paritytech/try-runtime-cli --tag v0.3.3
```
2. Save a snapshot of westend state to disk
```bash
try-runtime create-snapshot --uri wss://westend-rpc.polkadot.io:443 westend.snap
```
3. Checkout branch `liam-improve-try-state-tuple-internals` (unless https://github.com/paritytech/polkadot-sdk/pull/2019 is merged)
4. Comment out these problematic lines that cause try-state checks to take forever
https://github.com/paritytech/polkadot-sdk/blob/ff3a3bca449a3cae910d2dc8c7ed3658938c6478/substrate/frame/bags-list/src/list/mod.rs#L554-L558
5. Build westend runtime and run the try-state checks using `on-runtime-upgrade` (ideally would use `execute-block`, but that doesn't support snapshots yet https://github.com/paritytech/try-runtime-cli/issues/29)
```bash
cargo b --features try-runtime -p westend-runtime -r && \
try-runtime \
    --runtime ./target/release/wbuild/westend-runtime/westend_runtime.wasm \
    on-runtime-upgrade --checks all \
    snap --path ./westend.snap
```

You'll see output like this
<img width="1491" alt="Screenshot 2023-10-25 at 16 06 36" src="https://github.com/paritytech/polkadot-sdk/assets/16665596/b09ed015-63c8-4543-a114-a810b155f078">

<img width="1491" alt="Screenshot 2023-10-25 at 16 06 52" src="https://github.com/paritytech/polkadot-sdk/assets/16665596/cd7386d5-10e6-4550-b20c-62432bd36c77">

highlighting the errors

**Comment by Ank4n** [comment]
> Staking has failing storage invariant: "NotController"

This is happening because there is an account `5G3rej8vFLEMVcJPeMBnaxRBATtPEj3cXkSPDT2iEgbkMgbs` which exists in the storage item `Bonded` but does not exist in `Ledger`. This should never happen.

[The account](https://westend.subscan.io/account/5G3rej8vFLEMVcJPeMBnaxRBATtPEj3cXkSPDT2iEgbkMgbs) had last transaction in July 2020 and I am not sure what happened (may be some oversight in a historical purging). It would be good to figure out why this happened, but this can be fixed by killing the storage key for this account in `Bonded`.

**Comment by Ank4n** [comment]
> FastUnstake has failing storage invariant: "the value of ErasToCheckPerBlock is greater than T::MaxErasToCheckPerBlock"

`ErasToCheckPerBlock` is a storage value that should be smaller than the config const `MaxErasToCheckPerBlock`. Seems like the mismatch is in Westend since almost the beginning (verified this was incorrect at [block #14479190](https://westend.subscan.io/block/14479190) as well). If trying to set via the the call `control` in pallet-fast-unstake, this would not be allowed but I guess somebody set the storage value directly.

Current values:
### Westend
MaxErasToCheckPerBlock = 1
ErasToCheckPerBlock = 2

-----

**Kusama and Polkadot are set up correctly..** 

### Kusama
MaxErasToCheckPerBlock = 1
ErasToCheckPerBlock = 1

### Polkadot
MaxErasToCheckPerBlock = 1
ErasToCheckPerBlock = 1

**Comment by Ank4n** [comment]
> NominationPools has lots of ED warnings
Same issue as https://github.com/paritytech/polkadot-sdk/issues/158

This should be fixed once NominationPools [migrates to V6](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/westend/src/lib.rs#L1549).

**Comment by Ank4n** [comment]
> VoterList takes forever to run, get stuck here

This is the culprit. It loops over 62k ListNodes in Westend, 14k and 44k in Kusama and Polkadot respectively. We should disable this part in CI as well.

https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/bags-list/src/list/mod.rs#L556
