### ISSUE TITLE
[FRAME Core] General system for recognising and executing service work

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot-sdk#206]
There is often work (read: a state-transition which is potentially heavy) which needs to be done in a pallet when certain circumstances are reached. This is generally done either:

1. By having checks in on-chain state-transitioning code which recognises these conditions and immediately conducts the resulting work.
2. By using the on-chain scheduler or `on_initialize` to periodically check for such conditions and conduct the resulting work if met.
3. By having a service transaction which has arguments describing the work to be done and an off-chain script which determines if and when there are parameters which would result in work being done (and an `Ok(Pays::No)` returned rather than a fund-consuming `Err`).

All three of these have drawbacks. (1) introduces serious complexity into the code, possibly making effective benchmarking of an operation impractical. (2) wastes on-chain compute and introduces inescapable codepaths into block execution dramatically increasing the severity of bugs. (3) requires custom scripts to be made and spreads code with the same concern between languages (Rust and scripts) and codebases (the main pallet and a script repo) hurting development and maintenance.

What would be ideal is a standard means of determining what work can be executed via an off-chain worker or script and describing that work. A single script or (better) off-chain worker would recognise and be able to create and submit all possible work items at any given time as "service transactions". Pallets would only need to declare:

- A `Task` data type (probably an `enum` like `Call`) which describes items of work.
- Then, for each such item of work:
  - any parameters which help specify the task;
  - a function to be run by an off-chain worker which inspects the pallet's state and enumerates tasks of this kind;
  - a function which checks that a particular value of the `Task` variant is indeed a valid piece of work (i.e. is contained in the prior enumeration);
  - a function which accepts a particular value of a Task variant and (if valid) does the appropriate work.

Code-wise, it could look like this:

```rust
/// Some running total.
#[pallet::storage]
pub(super) type Total<T: Config<I>, I: 'static = ()> =
StorageValue<_, (u32, u32), ValueQuery>;

/// Numbers to be added into the total.
#[pallet::storage]
pub(super) type Numbers<T: Config<I>, I: 'static = ()> =
StorageMap<_, Twox64Concat, u32, u32, OptionQuery>;

#[pallet::tasks]
impl<T: Config<I>, I: 'static> Pallet<T, I> {
	/// Add a pair of numbers into the totals and remove them.
	#[pallet::tasks(Numbers::<T, I>::iter_keys())]
	#[pallet::condition(|i| Numbers::<T, I>::contains_key(i))]
	#[pallet::task_index(0)]
	pub fn add_number_into_total(i: u32) -> DispatchResult {
		let v = Numbers::<T, I>::take(i).ok_or(Error::<T, I>::NotFound)?;
		Total::<T, I>::mutate(|(total_keys, total_values)| {
			*total_keys += i;
			*total_values += v;
		});
		Ok(())
	}
}
```

This task would be called into via a System-pallet extrinsic (either through the block-builder, an OCW, submitted via a script or even manually through a transaction) *without any further logic in the pallet whatsoever*. The extrinsic could be called something like `fn do_task(origin: OriginFor<T>, task: Task)`.

A custom `ValidateUnsigned` within the System pallet which recognises this extrinsic would ensure that the `condition` for the `task` is met prior to accepting it via an inherent/unsigned extrinsic (signed transactions can call it anyway and risk payment not being refunded). `tasks` would ensure that the OCW/script could easily determine parameters which passed this `condition`.

If there were ever a bad bug (i.e. if `add_number_into_total` errored or panicked), then it would be easy to just not include the task in the block and the chain could continue operating as usual.

This would massively facilitate lazy-migrations. It would allow Scheduler, Referenda and other `on_initialize` code to be adapted to avoid big problems if there are unexpected circumstances/errors. And it would improve overall transaction bandwidth by allowing non-time-critical ramifications to be uncoupled from time-critical state-transitions.

Tasks could be labelled feeless in which case an origin check is unnecessary for all tasks which are considered tasks in the pre-dispatch.

## TODO

- [ ] Task discovery and submission
  - [ ] Build-builder component
  - [ ] OCW component
  - [ ] Separate script
- [ ] Feeless tasks

**Comment by xlc** [comment]
Actually, it will be good if we have less macro magics.

Proposed syntax:

```rs
/// Some running total.
#[pallet::storage]
pub(super) type Total<T: Config<I>, I: 'static = ()> =
StorageValue<_, (u32, u32), ValueQuery>;

/// Numbers to be added into the total.
#[pallet::storage]
pub(super) type Numbers<T: Config<I>, I: 'static = ()> =
StorageMap<_, Twox64Concat, u32, u32, OptionQuery>;

struct AddNumberIntoTotal;
impl Task for AddNumberIntoTotal {
	const INDEX: u32 = 0;
	type Id = u32;

	fn all_tasks() -> Iterator<Self::Id> {
		Numbers::<T, I>::iter_keys()
	}

	// not very sure why this is needed. `all_tasks` should already filter out invalid tasks.
	fn condition(id: &Self::Id) -> bool {
		Numbers::<T, I>::contains_key(i)
	}

	fn run(id: &Self::Id) -> DispatchResult {
		let v = Numbers::<T, I>::take(i).ok_or(Error::<T, I>::NotFound)?;
		Total::<T, I>::mutate(|(total_keys, total_values)| {
			*total_keys += i;
			*total_values += v;
		});
		Ok(())
	}
}

#[pallet::tasks]
type AllTasks = (AddNumberIntoTotal, )
```

**Comment by sam0x17** [comment]
RE: @xlc 

> Proposed syntax:

FYI the current syntax I have built parsing support for lives here: https://github.com/paritytech/polkadot-sdk/pull/1343#issue-1876319076 and I have reproduced it below for reference:

```rust
#[pallet::task]
pub enum Task<T: Config> {
    Increment,
    Decrement,
}

/// Some running total.
#[pallet::storage]
pub(super) type Total<T: Config<I>, I: 'static = ()> =
StorageValue<_, (u32, u32), ValueQuery>;

/// Numbers to be added into the total.
#[pallet::storage]
pub(super) type Numbers<T: Config<I>, I: 'static = ()> =
StorageMap<_, Twox64Concat, u32, u32, OptionQuery>;

#[pallet::tasks]
impl<T: Config<I>, I: 'static> Pallet<T, I> {
	/// Add a pair of numbers into the totals and remove them.
	#[pallet::task_list(Numbers::<T, I>::iter_keys())]
	#[pallet::task_condition(|i| Numbers::<T, I>::contains_key(i))]
	#[pallet::task_index(0)]
	pub fn add_number_into_total(i: u32) -> DispatchResult {
		let v = Numbers::<T, I>::take(i).ok_or(Error::<T, I>::NotFound)?;
		Total::<T, I>::mutate(|(total_keys, total_values)| {
			*total_keys += i;
			*total_values += v;
		});
		Ok(())
	}
}
```

This is almost identical to Gav's proposed syntax introduced above (https://github.com/paritytech/polkadot-sdk/issues/206#issue-1865172283) with a few naming changes for clarity and some pieces that weren't included in his original example like the `#[pallet::task]` enum that are necessary for all these pieces to work together.

The way I have implemented the syntax, you should be able to manually impl `Task` like you do above (pending 1-2 tweaks I need to push up) if you want to be more verbose, and in fact this is a first-class feature because the way I have evolved the `tasks-example` pallet is to start with manual syntax like you have and slowly replace each piece with the macro accomplishing the same thing. I will make sure to keep this in mind and include a UI test that this still works when I am done if it would make you happier. I totally agree that we should always be able to manually impl stuff without using macros whenever feasible, and I'd like to support that as best as I can here. For me one of the stronger arguments for this is that it makes it much easier to debug macro expansions if the expansions themselves are supported syntax, so doing so is of course a win for everyone.

The only place where your syntax seems to differ from the above is tasks behave like events and errors in my syntax so there is a `#[pallet::task]` enum instead of it just being a tuple type. 

I have no problem with leaving it open such that if `#[pallet::task]` isn't present anywhere it will just look for an impl statement impling the `Task` trait on something, and that something will be assumed to be an enum that should be aggregated as part of `RuntimeTask`. **This should allow you to completely omit the task-related macros if you wish.**

One thing I _don't like_ about my syntax is I don't think it is very clear that `#[pallet::task]` is for the task enum... I followed this convention to match how call and error work but I do think `#[pallet::task_enum]` would be clearer and I would be happy to make that change since there are also other task-related attributes and intuitively, I would think `#[pallet::task]` would actually be applied to a specific task for example, and not the task enum. So I will probably do that rename of `#[pallet::task]` => `#[pallet::task_enum]` for 100% clarity.

but yes @xlc thank you for making the point that we want to make the macro syntax as optional as possible and I will stay true to that.

cc @gavofyork @kianenigma

**Comment by gavofyork** [comment]
Seems fine except for the requirement to declare the items within `Task` unlike with `Call`.

**Comment by sam0x17** [comment]
Yeah retrofitting so we can omit the enum entirely and auto-generate it from the impl 👍🏻

**Comment by gavofyork** [comment]
Reopened as task-dispatch is still very much unfinished.
