### ISSUE TITLE
Disablement: Dispute participation disabling

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2225]
Some thoughts: https://github.com/paritytech/polkadot-sdk/issues/784#issuecomment-1765014451
More implementation hints (more concrete, should resolve the above): https://github.com/paritytech/polkadot-sdk/issues/784#issuecomment-1834113808

**Comment by eskimor** [comment]
@ordian please notes on era changes and handling.

**Comment by Overkillus** [comment]
Re: node side disablement

We added node side disablement to fight against cases where the offending validator is no longer in the active validator set but he commits an offence in the previous era. (Correct?)

If in era n+1 a bunch of honest validators got slashed for 0% and they occupy the 1/3 disablement limit then an offender in era n will not get node-side disabled since the runtime has a priority.

Is this an issue? How easy it is to exploit it? It seems to somewhat go against the property of re-enabling as across eras we have the safety as if we didn't have re-enabling.

**Comment by eskimor** [comment]
This is totally fine. The reason we want re-enablement is to prevent a flatrate for trying to back an invalid candidate. The node side disabled list is only needed for spammers.
