### ISSUE TITLE
Compilation of sp-core fails in polkadot-v1.3.0

### ISSUE THREAD

**Issue by louismerlin** [paritytech/polkadot-sdk#2327]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Compilation of sp-core in `polkadot-v1.3.0` fails.

The root issue seems to come from references to pallets in [ring-vrf](https://github.com/w3f/ring-vrf).

```
...
   Compiling bandersnatch_vrfs v0.0.1 (https://github.com/w3f/ring-vrf?rev=4b09416#4b09416f)
error[E0616]: field `keyset_part_size` of struct `ring::PiopParams` is private
  --> /path/to/.cargo/git/checkouts/ring-vrf-fa8519651343a7ee/4b09416/bandersnatch_vrfs/src/ring.rs:70:26
   |
70 |         self.piop_params.keyset_part_size
   |                          ^^^^^^^^^^^^^^^^ private field

For more information about this error, try `rustc --explain E0616`.
error: could not compile `bandersnatch_vrfs` (lib) due to previous error
...
```

### Steps to reproduce

Tested using Rust stable-x86_64-unknown-linux-gnu, rustc 1.73.0 (cc66ad468 2023-10-03).

```
cargo new test-project
cd test-project
cargo add sp-core --git https://github.com/paritytech/polkadot-sdk --tag polkadot-v1.3.0
cargo build
```

**Comment by burdges** [comment]
Yes, I fucked this one up, approved a PR to a git dependency without properly checking it.

I'll merge https://github.com/w3f/ring-vrf/pull/73 tomorrow if sergey does not merge https://github.com/w3f/ring-proof/pull/15

If you need it faster then I can merge it anyways.

**Comment by davxy** [comment]
@burdges  https://github.com/w3f/ring-vrf/pull/73#event-10973203634 should not be merged as it will badly break some unit tests in substrate bandersnatch wrapper 

https://github.com/paritytech/polkadot-sdk/blob/ea4085ab7448bb557a1558a25af164cf364e88d6/substrate/primitives/core/src/bandersnatch.rs#L810

As the integration of sassafras pallet is really close (I hope to merge it for eow)  IMO at this point we need to choose between:
- pay **really** more attention to breaking changes in `bandersnatch_vrfs` and `ring-proof`
- change version of `bandersnatch_vrf` to 0.1.0 and publish it on crates.io so that we don't break polkadot-sdk builds so easily

Now this stuff is used on `polkadot-sdk` master so IMO we need an action.

I vote to publish a working one on crates.io so that you can in the meantime experiment more freely with the git repo

**Comment by burdges** [comment]
Alright we'll wait for @swasilyev then

**Comment by burdges** [comment]
It should be fixed via my temporary hack..  we'll wait for the ring-proof crate to be updated for the real fix.

**Comment by notlesh** [comment]
In case anyone needs a quick fix, see [this commit](https://github.com/keep-starknet-strange/madara/pull/1264/commits/55f0a6805d87907229fdf03820164ed78594bd23).

Note, in particular, that I needed to use [this workaround](https://stackoverflow.com/a/72261235) to avoid the error `patch for bandersnatch_vrfs in https://github.com/w3f/ring-vrf points to the same source, but patches must point to different sources`.
