### ISSUE TITLE
Disputes raised due to `RuntimeConstruction` error in pvf execution

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#2863]
The issue is happening on Rococo, logs: https://grafana.teleport.parity.io/goto/BQfD20FSg?orgId=1

`
WARN tokio-runtime-worker parachain::dispute-coordinator: Candidate 0x0008ce7fe58231c871fda90dd6fbf140fc5961bf0fad7301139340406a64bc63 considered invalid: ExecutionError("execute: execute error: RuntimeConstruction(Other(\"cannot deserialize module: compilation settings of module incompatible with native host: compilation setting \\\"has_avx512bitalg\\\" is enabled, but not available on the host\"))")
`

`
WARN tokio-runtime-worker parachain::pvf: execution worker concluded, error occurred: Invalid(WorkerReportedInvalid("execute: execute error: RuntimeConstruction(Other(\"cannot deserialize module: compilation settings of module incompatible with native host: compilation setting \\\"has_avx512bitalg\\\" is enabled, but not available on the host\"))")) artifact_id=ArtifactId { code_hash: 0x90efa66f83c794ea1ce93f4a7f019a389a6ba151493326bd790e49077515f369, executor_params_hash: 0x03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314 } worker=Worker(2v1) worker_rip=false
`

` WARN tokio-runtime-worker parachain::approval-voting: Detected invalid candidate as an approval checker. reason=ExecutionError("execute: execute error: RuntimeConstruction(Other(\"cannot deserialize module: compilation settings of module incompatible with native host: compilation setting \\\"has_avx512bitalg\\\" is enabled, but not available on the host\"))") candidate_hash=0xa9a745a082c2aadb0077a421b5902be4ef54f4c1f5d0da4871edd2ca65e0ca09 para_id=Id(2030) traceID=225508057066263142710214066364837014500
`

To answer why is this happening, requires more digging. One possible answer is the host VM type was changed. But, in any case we shouldn't raise a dispute for candidates that we can't check due to such errors.

CC @s0me0ne-unkn0wn @mrcnski

**Comment by bkchr** [comment]
The reason is probably that the VM was moved and as we don't clean up the cache anymore since https://github.com/paritytech/polkadot-sdk/issues/685, we see this problem.

The solution should be that we include the host architecture as well in the artifact name.

**Comment by s0me0ne-unkn0wn** [comment]
@mrcnski probably it's perfect timing for fixing it in the scope of #2604?

**Comment by mrcnski** [comment]
Ah no!

1. Maybe we should actually try constructing the runtime for each artifact on node startup, and prune any that fail. 
2. And yeah, we should as well include the host architecture in the artifact name, in case a mismatch could also lead to other errors apart from runtime construction. (i.e. runtime construction succeeds but execution fails due to architecture mismatch - not sure if it's possible?) Any other info that would be good to include?

Also related: https://github.com/paritytech/polkadot-sdk/issues/661. The tl;dr is that I didn't have confidence to treat `RuntimeConstruction` as an internal error, though it *should* be safe to do so. It is rather overloaded and needs some untangling.

Good that this only happened on Rococo so far. We should make this a high-priority fix!

**Comment by mrcnski** [comment]
> @mrcnski probably it's perfect timing for fixing it in the scope of #2604?

You mean, do the considered refactor of preparation errors? This PR title is inaccurate because the logs indicate the error is in execution, not preparation. Indeed I was confused at first because preparation errors should never raise a dispute - will update the title. Or did you mean something else?

**Comment by mrcnski** [comment]
> The tl;dr is that I didn't have confidence to treat RuntimeConstruction as an internal error, though it should be safe to do so. It is rather overloaded and needs some untangling.

Actually we can do this now, I forgot about this: https://github.com/paritytech/polkadot-sdk/issues/661#issuecomment-1817944683 For the record, the concern was that the [`Other` variant](https://github.com/paritytech/substrate/blob/2e94e25395/client/executor/common/src/error.rs#L158) specifically is overloaded - ideally for errors that we treat as internal, we have enumerated every error case.
