### ISSUE TITLE
Kusama slash era 6131

### ISSUE THREAD

**Issue by Ondin777** [paritytech/polkadot-sdk#2975]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

Hi to all readers, on Era 6131 my Validator Ondin3 E62PfJNuJpyKqTy3JU8D6LiuKagafiJJ9sLJsJHQShPVa4R was slashed without action by me. During the night of 14 Jan (00:53-1:53 AM) the data center where I am, has suffered a problem that lead to electricity to be cut for 1 hour, as soon as the electricity went back my validators went up again and no action from me was made except to re-enable the validating intention again. For some reason the process of ONDIN3 crashed leading to the slash you see on the network, no change of session key or any other type of backup was made so there was no chance of double signing. The node reporter of the slash was my other validator ONDIN2 that went online again together with ONDIN3 (different server but under the same /24) . I have attached the logs of Ondin3 and I ask to review my slash because it was not caused by my actions but from an exception of event 
[ondin_slash.txt](https://github.com/paritytech/polkadot-sdk/files/13969002/ondin_slash.txt)

```[tasklist]
### Tasks
```

**Comment by andresilva** [comment]
I looked at the logs and we can't deduce anything from it. My only explanation for what happened is that when the node shutdown due to electricity being cut it didn't persist what he had voted on, which meant that when the node was restarted it voted again, leading to an equivocation. There isn't much we can do if the node just shuts down abruptly due to the computer it runs on being turned off.

We can't do anything about the slash itself, that is a job for the chain governance.
