### ISSUE TITLE
Fix provisioner issue for on-demand/coretime

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#3141]
Provisioner code does not seem to be fully on-demand ready.

https://github.com/paritytech/polkadot-sdk/blob/a02b53475b9fe2567ae05ad4e03c81f4f3d6b463/polkadot/node/core/provisioner/src/lib.rs#L662

**Comment by antonva** [comment]
This should be fine and is generally the same as https://github.com/paritytech/polkadot-sdk/issues/664,
which is that `next_up_on_available()` used to use the `CoreIndex` to index into the `paras::parachains()` vec directly to map to a `ParaId`.

Ever since we refactored this out of the scheduler and into the `AssignmentProvider` interface we no longer have this assumption.

**Comment by alindima** [comment]
Having a deeper look at the code and speaking with @antonva about this, we came to the following conclusion:

Assume core A is occupied by Para1, the `next_up_on_available` is Para2 and the bitfields for making the candidate of Para1 have been recorded on-chain.
The next block producer will call the provisioner, which will request from prospective-parachains the next backable candidate of Para2, which has the Para1 candidate as parent. There's obviously no such candidate so the core will transition to scheduled.
Para2 will be able to get a candidate in the next iteration.

So it's a slight inefficiency that is made less likely due to the core affinities.

I suggest we fix it by modifying the provisioner to check if the newly scheduled para is different than the previous one and if it is, request a backable candidate with the required_path of the new para instead (taking into account a possible parent candidate for Para 2 present on another core)

**Comment by alindima** [comment]
I found a very similar problem in collation-generation: https://github.com/paritytech/polkadot-sdk/issues/3327
