### ISSUE TITLE
 [RelEng] Automate node release process

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3291]
Same as #3290 but for the node.  

```[tasklist]
### Steps
- [ ] https://github.com/paritytech/polkadot-sdk/issues/4393
- [ ] https://github.com/paritytech/release-engineering/issues/217
- [x] Setup runner config
- [x] Publish the node once with manual trigger
- [ ] https://github.com/paritytech/release-engineering/issues/214
```

**Comment by EgorPopelyaev** [comment]
Awaits a new release org which is to be prepared by @pavelsupr

**Comment by pavelsupr** [comment]
> Awaits a new release org which is to be prepared by @pavelsupr

@EgorPopelyaev, it shouldn't be dependent on the release org per se, because the pipeline code should be written originally in the main org. The release org is basically set of forks with no additional code, but with some specific repo and org settings. And it is just another location of the actual execution of the pipeline code. I.e. before this code is executed in th release org, it should already exist in the main org, to be synced with no changes by the fork api.

Current status of that btw: I've been waiting for the approval for the paid tier of GH orgs, expecting to get this and finish the setup by 10-11 Jul.

**Comment by EgorPopelyaev** [comment]
True, the preparation can be and beeing done in parallel. I only mean by that, that at the and as final step it will need the org anyway to be tested and start to work in it's final implementation :)

**Comment by EgorPopelyaev** [comment]
This one can be closed now, the latest stable release is done completely based on the pipelines in GitHub
