### ISSUE TITLE
[CI] Prevent breaking changes in minor/patch bumps

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3292]
Part of https://github.com/paritytech/polkadot-sdk/issues/3046  

We need to create a Merge Request CI check to sanity check all crates' public API.  
If the API or a crate changed, then there must be a major bump.

There are some tools for this:
- https://crates.io/crates/cargo-public-api
- https://crates.io/crates/cargo-semver-checks

The check can probably be optimized to only check all modified crates and their direct&transitive dependants.  
We also need to take [`__private` exceptions](https://github.com/paritytech/polkadot-sdk/blob/master/docs/RELEASE.md#crate) into account.

**Comment by obi1kenobi** [comment]
👋 Hey! I'm the `cargo-semver-checks` maintainer. Let me know if you run into any issues with the tool.

If you want it to ignore certain items that aren't public API, the best way to do that is to mark them `#[doc(hidden)]` since that's the usual convention Rust seems to have settled on in general. `cargo-semver-checks` already ignores `#[doc(hidden)]` items, and it also by default ignores [features with names like `unstable` or other names that imply non-stability](https://github.com/obi1kenobi/cargo-semver-checks?tab=readme-ov-file#what-features-does-cargo-semver-checks-enable-in-the-tested-crates).

If anything in our FAQ is unclear or not documented, or you run into any issues, let me know and I'll be happy to take a look.

**Comment by bkchr** [comment]
@Morganamilo @ggwpez we will need to prevent that people put the `silent` label on any pr that touches code which is in a crate with `publish = true`. 

Maybe a problem with test only changes, but these should be quite rare.

**Comment by ggwpez** [comment]
The original goal of this issue is solved.

>we will need to prevent that people put the silent label on any pr that touches code which is in a crate with publish = true.

Included here: https://github.com/paritytech/polkadot-sdk/issues/4817
