### ISSUE TITLE
Look-ahead collator: build on all assigned cores

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#3837]
https://github.com/paritytech/polkadot-sdk/pull/3795 introduces some changes that allow the look ahead collator to specify which core a collation should be backed on. We need to implement something similar to what that PR does for the test collators which use collation pull via `collator_fn`.

**Comment by bkchr** [comment]
> Also this is a breaking change and I would expect people still be using it for a while before they invest to swtich.

No one is currently using the lookahead collator. So you can bring the argument for switching to it as well ;)

@skunert already told you that he can deliver a first version that supports multiple cores this week or the next week.

**Comment by skunert** [comment]
IMO it is fine to implement something for the lookahead collator if you want to get something running quickly for testing. However, integration will be non-optimal, since the lookahead collator only knows about relay triggered block production. If you just want to produce more blocks and submit them, that is not hard to integrate. They will be build directly in succession if you we do not build any kind of slot logic into it. Which brings us  to #3168 . 

As far as breakage goes, the way we author the blocks themselves does not change. So if you have a chain that has 6s slot time, I think we can make the slot-based authoring compatible.

As for ETA, AFAIR we aligned on April in the last sync meeting, but I think some initial version can come sooner, as I wrote in element.

**Comment by sandreim** [comment]
> > Also this is a breaking change and I would expect people still be using it for a while before they invest to swtich.
> 
> No one is currently using the lookahead collator. So you can bring the argument for switching to it as well ;)
> 

IIRC we are using it for our system parachains and people are supposed to use it for async backing which is something we are enabling on Kusuma/Polkadot right after the runtime upgrade.

**Comment by bkchr** [comment]
"Supposed to use" and what people are doing are two different things ;) Also they are not required, because block production will continue to work as before.
