### ISSUE TITLE
sc-authority-discovery: test `addresses_to_publish_respects_existing_p2p_protocol` broken

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#3887]
---- worker::tests::addresses_to_publish_respects_existing_p2p_protocol stdout ----
thread 'worker::tests::addresses_to_publish_respects_existing_p2p_protocol' panicked at substrate/client/authority-discovery/src/worker/tests.rs:739:5:
assertion `left == right` failed: Expected Multiaddr from `TestNetwork` to not be altered.
  left: ["/ip6/2001:db8::/tcp/30333/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC"]
 right: ["/ip6/2001:db8::/tcp/30333/p2p/12D3KooWNpFd1iMHjm3Q5gqQs4uJufVTDM7GY4aMcFueTWafHkyt"]

fails with https://github.com/paritytech/polkadot-sdk/pull/3885

**Comment by sandreim** [comment]
CC @dmitry-markin @alexggh

**Comment by alindima** [comment]
CC @lexnv, I think you recently had some changes to authority-discovery: https://github.com/paritytech/polkadot-sdk/commit/5ac32ee2bdd9df47e4578c51810db4d2139757eb

**Comment by dmitry-markin** [comment]
Most likely the test started failing after my PR https://github.com/paritytech/polkadot-sdk/pull/3757. I don't know how it sneaked in, probably because it was disabled in the CI.

https://github.com/paritytech/polkadot-sdk/pull/3757 changes the logic so that the `/p2p/...` protocol of the multiaddress is always overwritten with the local `PeerID`. In the test in question we put some arbitrary `PeerID` into external address, and of course, it's replaced with the correct `PeerID`.

I don't think the test makes sense in it's current form. I will create a PR to fix/remove the test and, additionally, to generate an error if it happens that the external address reported by the network backend contains PeerId different to the one of the node (with the libp2p network backend external addresses do not contain any `/p2p/...` components).

**Comment by sandreim** [comment]
We should be able to merge https://github.com/paritytech/polkadot-sdk/pull/3885 once your fix is merged in master.
