### ISSUE TITLE
Small network finality stall (Westend)

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#4149]
Similar to: https://github.com/paritytech/polkadot-sdk/issues/3596

In the past months we have observed that on small networks such as Westend finality stalls even with very low approval voting settings like:
- `neededApprovals: 2`
-  `nDelayTranches: 40`
- `relayVrfModuloSamples: 1`

Network size 18 validators and 6 parachains.

The reason based on the logs is that at least 1/3 of validators don't have the required approval votes(2) for one candidate and don't finalize the including block:
- https://grafana.teleport.parity.io/goto/wX8sMBaIR?orgId=1
- https://grafana.teleport.parity.io/goto/XSminBaIR?orgId=1

Log samples (westend-validator-a-node-1)  
`parachain::approval-voting: Unapproved candidates at depth 143: [0xe786b217208ec0aea725a96469e82ffea98dca7bad15c2a6c1deff84e9f76f99] block_hash=0x68cc3da9488a70b2b4ab13b1f05a25ba6f6e73093b89f952ec8a906c4e776911`

While `westend-validator-d-node-2` seens that block approved:
`DEBUG tokio-runtime-worker parachain::approval-distribution: Received `ApprovalCheckingLagUpdate` lag=0`

This behaviour looks like a small network specific approval voting bug. We need to reproduce this scenario with Zombienet and find root cause.

**Comment by alexggh** [comment]
I think I now the root cause here, looking at the logs, from here: https://grafana.teleport.parity.io/goto/LRXvLYaIR?orgId=1.

The first thing that triggers me is `5/5/18` which tells me that this candidate has 5 assignments and 5 approvals, so it should have been approved, however that doesn't happen because of a series of events.
```
2024-04-15 13:32:44.572 DEBUG tokio-runtime-worker parachain::approval-voting: assigned. candidate_hash=0xe786b217208ec0aea725a96469e82ffea98dca7bad15c2a6c1deff84e9f76f99 block_hash=0x68cc3da9488a70b2b4ab13b1f05a25ba6f6e73093b89f952ec8a906c4e776911 tranche=0 next_wakeup=None status=5/5/18 triggered=true approved=true traceID=307751046906592519065228463061670047742
```

## Rootcause

1. We have a fork chain with  2 blocks including `0xe786b217208ec0aea725a96469e82ffea98dca7bad15c2a6c1deff84e9f76f99`.

2. Kagome validators gets an assignment on tranche0 on both blocks:
```
2024-04-15 13:31:48.228 TRACE tokio-runtime-worker parachain::approval-voting: Imported assignment for a single core. validator=8 candidate_hashes=[0xe786b217208ec0aea725a96469e82ffea98dca7bad15c2a6c1deff84e9f76f99] assigned_cores=[CoreIndex(3)]
2024-04-15 13:31:48.229 TRACE tokio-runtime-worker parachain::approval-voting: Imported assignment for a single core. validator=8 candidate_hashes=[0xe786b217208ec0aea725a96469e82ffea98dca7bad15c2a6c1deff84e9f76f99] assigned_cores=[CoreIndex(3)]
```
3.  For whatever reason kagome decides to send its approval at the exact no-show window and it sends just one approval for the candidate instead of sending it twice for both relay chain blocks like we do it in `polkadot-sdk`

4. Polkadot-sdk count vote per candidate in CandidateEntry, so sending an approval for a candidate in the context of R1 might cause it to be approved in the context of R1' as well. However, there is a race on that path because Candidates are marked as approved in advance_approval_entry(candidate, relay_chain_hash) and that gets called in two situations,  when received an approval in the context of relay chain block, or when process_wakeup gets called.

5. So if process_wakeup in the context of R1' gets called after we received the approval for candidate_entry in the context of R1 we are going to mark the candidate approved in the context of R1' as well and not trigger any extra assignment.

6. For all nodes a wakeup is called on the next_no_show or on the moment we need to trigger our assignment, because kagome sends its approval in the context of R1 after no show periods process_wakeup will get called only on the nodes that have un-triggered assignments only those will decide to mark candidate as approved in the context of R1'.

7. This is problematic in this case because we end-up splitting the network in  two parts nodes that didn't approved the candidate in the context of R1' and nodes that approved it. This is bad because of two reasons, no new assignments and approvals will get triggered by the nodes that approved the candidate in the context of R1, so the nodes that have the candidate unapproved need to triggered a new assignment to advance the approval-state, however that won't happen because in that set we have 7 nodes which are the nodes that triggered already their assignment and nodes that backed the candidate.

Westend 18 nodes large so 7 nodes, will be enough to stall finality, however this race is not a problem on bigger networks because there the backing_group size is way smaller than 1/3 of the nodes.

**Comment by burdges** [comment]
Do we know if all candidates are getting those two approval checkers?  It's always possible we've some bug in the odds for assigning approval cehckers, which results in none being assigned.

**Comment by alexggh** [comment]
We know for sure that only those 7 have an approval lag, and the rest of 11 have the candidate as approved, so the 11 won't trigger any new assignment because they have the candidate approved, and 7 can't trigger new assignment because they either triggered their or they were in the backing-group. The thing is the candidate already has 5 approvals out of 5 assignments, so it should be enough, we just don't have a wake-up that would mark the candidate approved in the database,  hence why I think https://github.com/paritytech/polkadot-sdk/pull/4153 would fix it.

**Comment by burdges** [comment]
Yes, https://github.com/paritytech/polkadot-sdk/pull/4153 sounds like the right direction.

We still have backing group sizes of five?  Interesting, but maybe that's too painful to change for these chains.

We might ignore backing group sizes in some computation somewhere, which maybe screws up our parameters when the backing group becomes proportionally so large.

**Comment by sandreim** [comment]
Fixed by https://github.com/paritytech/polkadot-sdk/pull/4153
