### ISSUE TITLE
Nomination pools: points to balance and balance to points rounding inaccuracy

### ISSUE THREAD

**Issue by gpestana** [paritytech/polkadot-sdk#416]
It has been [reported](https://hackmd.io/OHDPAxEHQq6O6EP_9zzCag) that a conversion of `points_to_balance` in nominations pools returned less balance than expected (in Westend). In summary, an account joined a pool with 4 WND and -- even though there was no unbonding or slashes in the pool -- the result of calling the `points_to_balance` with the received points when joining is 399.999 mWND.

The runtime API is using the same logic for calculating the `points_to_balance` and `balance_to_points` as used when accounts join/leave pools.

**Comment by SCJangra** [comment]
We are also experiencing something similar in our chain. I bonded 5000 tokens in a new (never slashed) pool and the actual bonded points was around 3.4.

It happened because of the this code.
https://github.com/paritytech/polkadot-sdk/blob/311266a9c09e421d82dec0f4936b47d245baa2a3/substrate/frame/nomination-pools/src/lib.rs#L2957-L2960C27

Note that the conversion back to `Balancd` type (in our case `u128`) happens just after multiplication, which overflows and therefore, in our case, saturates the balance type to its maximum value. And if we then divide it by `new_funds`, we get a much smaller value than expected. So the conversion back to `Balance` type should happen after the actual result has been computed, which is after division.

This example demonstrates this.
```rust
use sp_core::U256;

fn u256(value: u128) -> U256 {
	U256::from(value)
}

fn balance(value: U256) -> u128 {
	value.try_into().unwrap_or(u128::max_value())
}
fn main() {
	// We are using 18 desimals
	let current_balance = 100_000_000_000_000_000_000_u128; // 100 Tokens
	let current_points = 100_000_000_000_000_000_000_u128; // 100 Tokens
	let new_funds = 5_000_000_000_000_000_000_000_u128; // 5000 Tokens

	let actual = balance(u256(current_points) * u256(new_funds)) / current_balance;
	let expected = balance(u256(current_points) * u256(new_funds) / u256(current_balance));

	// Prints 3402823669209384634, about 3.4 Tokens
	println!("{actual}");
	// Prints 5000000000000000000000, 5000 Tokens
	println!("{expected}");
}
```
