### ISSUE TITLE
[NPoS] Nomination pools: Allow funds to be used for democracy

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#454]
Edited:

Nomination pool currently works by 1) moving the funds from delegator to pool account, and 2) stake from pool account.
What we really want though is, 1) delegate the funds from delegator to pool account, and 2) stake from pool account.

Delegate the funds would imply similar pool functions with a very important difference that instead of funds moving from delegator to pool account, the funds will be locked in delegator's account and can be used for participating in governance voting.

In https://github.com/paritytech/polkadot-sdk/issues/408, staking pallet will enable the functionality of delegation of funds to another account (such as pool account) which will enable nomination pools to achieve the `delegate and stake` strategy. By utilising the delegated funds as if they belong to the pool, the pool account gains the ability to stake these funds as a direct nominator.

**Comment by forgetso** [comment]
Thanks for the update @kianenigma

**Comment by michalisFr** [comment]
Since this is already being worked on, this is mostly for the sake of discussion, but let me post an alternative solution.

With the current way that pools work (funds being sent to the pool), pool members could opt in to delegate their funds in the pool to the pool (to keep things simple delegating is binary, either their whole stake or nothing). A new `capital` variable for the pool would need to be introduced that would keep track of the total delegated balance (from the members that have opted in). Then the pool (through its owner account) would be able to vote in referenda with this capital. The conviction should be limited to None, otherwise pool members may not be able to unbond.

Basically this wouldn't be a delegation per se, but an internal mechanism of pools that allows them to have a capital (not necessarily equal to the pool account's balance) with which the pool can vote in referenda.

Is what I'm describing possible? What would be the benefits and drawback compared to the solution you're working on @Ank4n?

Some pros of the solution you work on that I can think of:
1. Funds remain in the user's account -> increased "sense" of security and similar experience to solo staking
2. User can decide for themselves how to vote or delegate their vote
3. Doesn't centralise voting power in the hands of pool operators (as my proposal does). But given that delegation is encouraged, I consider this more of a con than a pro (see my second point below).

Some pros of my proposed solution:
1. Simpler implementation (I think)
2. Users that join a pool some times do it as a simpler solution to staking, even if they can stake solo. These users are not likely to participate in governance. On the other hand, pool operators are likely to vote in referenda and if they carry the votes of their pool's members, this would lead to increased participation. In other words, it would be a simple way for pool members to delegate their votes, even simpler than the current delegation method.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/retail-nominators-the-foundation-of-dot-demand-until-polkadots-next-chapter/4252/16

**Comment by michalisFr** [comment]
> @michalisFr Sorry for the late response (i am in a retreat currently), but sounds a decent idea. Especially if we make it even simpler and allow all pool funds to be used in governance by the pool operator. A pool can signal at the time of creation whether the pool funds will be used for governance. The only con I see is that delegators can't independently vote on a referenda but that may not necessarily be a bad thing.

Hey @Ank4n! No worries. Thanks for the response.

This is indeed an even simpler solution. How would you handle existing pools and members though? If this was to be allowed for existing pools (as it should IMO), some members might disagree with their pool's decision, but leaving a pool is not easy.

Anyway, these are implementation _details_. I don't want to take up more of your time with this. Unless you're actually thinking of going with this model over the one you're already working on :)

**Comment by forgetso** [comment]
>  The only con I see is that delegators can't independently vote on a referenda but that may not necessarily be a bad thing.

Not being able to vote when your funds are in a nomination pool is highly problematic.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/frame-monthly-update/4628/1

**Comment by muddlebee** [comment]
hey @Ank4n any estimated timeline for this? I'm a community mod at Polkadot discord, we are getting frequent queries about when this will be live.

**Comment by Ank4n** [comment]
> hey @Ank4n any estimated timeline for this? I'm a community mod at Polkadot discord, we are getting frequent queries about when this will be live.

Hey @muddlebee, unfortunately this turned out to be a much bigger change and we had some back and forth on how we want to implement this without adding regression to current staking logic. But there is progress on it in [this PR](https://github.com/paritytech/polkadot-sdk/pull/2680) and seems to be the approach we are settling on. My current target is to get this to Westend in Q1 but for Kusama and Polkadot, I would say Q2 (with audit).

**Comment by Ank4n** [comment]
Update: Moved it to Q1 2024 in the roadmap.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/monthly-governance-incentive-referendum-1-buffet/5764/2

**Comment by sourabhniyogi** [comment]
> > hey @Ank4n any estimated timeline for this? I'm a community mod at Polkadot discord, we are getting frequent queries about when this will be live.
> 
> Hey @muddlebee, unfortunately this turned out to be a much bigger change and we had some back and forth on how we want to implement this without adding regression to current staking logic. But there is progress on it in [this PR](https://github.com/paritytech/polkadot-sdk/pull/2680) and seems to be the approach we are settling on. My current target is to get this to Westend in Q1 but for Kusama and Polkadot, I would say Q2 (with audit).

Can you explain what exactly is locked by a pool operator who votes on referenda with a certain level of convictionVoting?

**Comment by Ank4n** [comment]
> > > hey @Ank4n any estimated timeline for this? I'm a community mod at Polkadot discord, we are getting frequent queries about when this will be live.
> > 
> > 
> > Hey @muddlebee, unfortunately this turned out to be a much bigger change and we had some back and forth on how we want to implement this without adding regression to current staking logic. But there is progress on it in [this PR](https://github.com/paritytech/polkadot-sdk/pull/2680) and seems to be the approach we are settling on. My current target is to get this to Westend in Q1 but for Kusama and Polkadot, I would say Q2 (with audit).
> 
> @Ank4n In your Q1 2024 delivery (exciting, thank you for moving it up!), can you explain what exactly will be locked by a pool operator who votes on referenda with a certain level of convictionVoting, if pool funds can be used for governance?

I am not sure if I understood the question. Once this is live, funds contributed to nomination pool would be held (reserved) in user's own account instead of being transferred to the pool's account. Any pallet such as pallet-conviction-voting that looks at total balance and uses freezes (locks) would be able to reuse these held funds. Did that answer your question?

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/opengov-improvements-on-the-technical-level/6578/3

**Comment by bkchr** [comment]
@Ank4n @gpestana can someone of you give an update on the status of this issue?

**Comment by Ank4n** [comment]
PR here https://github.com/paritytech/polkadot-sdk/pull/2680. Its very close to being ready.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/paritytech-update-for-april/7646/1

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/paritytech-update-for-april-2024/7646/2

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/any-update-on-voting-while-staking-in-a-pool/8589/3
