### ISSUE TITLE
Claim queue: Remove TTL

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#4776]
and occupied cores + timeout retries.

All we really need to do on block import in the scheduler is:

1. Look into the claim queue on position 0 for a given core to check whether provided candidates match what is expected.
2. 
    a. If the core was occupied and got freed due to bitfields (or timeout): drop head of queue and fill back from assignment provider.
    b. If the core was not occupied: drop head of queue and fill back from assignment provider.
    c. If core was occupied and does not get freed: Keep claim queue as is.

The reason for (2c) is on-demand: There is no reason to drop good orders just because one core takes a bit longer to get freed.

With this the scheduler should finally only be concerned with scheduling and does not even need to know whether a core is occupied or not, all it does is providing scheduling entries and API users (inclusion) can move the queue forward as they see fit: Full separation of concerns.

Basically the API of the scheduler should look something like this:

```rust
/// Get all claim queues for all cores, to expose via runtime API:
fn get_claim_queues() -> Map<CoreIndex, ClaimQueue>;

/// Get next scheduled item. (used in (1) above:
fn scheduled_on_core(CoreIndex) -> Option<ParaId>;

/// Pop first item in claim queue for core and return it.
///
/// Claim queue size is preserved by backfilling at the end from the assignment provider (if possible).
fn advance_claim_queue(CoreIndex) -> Option<ParaId>;
```

That's it. We don't do retries on timeout as they only really make sense for on-demand anyways and provide very little value in general. The handling and tracking of occupied cores (and timing them out) will be left fully to the inclusion pallet.

Side-effect of this cleanup should be that the claim queue finally will always have the correct size.

@ordian @alindima

**Comment by alindima** [comment]
@eskimor I've spent some time prototyping this and I think it's worth pointing out that what you proposed here adds a fundamental difference to what the claim queue is storing (assuming I understood what you proposed, correct me if I'm wrong):

the topmost item in the claim queue will no longer be popped when something gets backed. It will be popped when a candidate gets included or times out during availability or if a candidate does not get backed (slot was missed).
Now, I don't see anything wrong with this, just something worth pointing out. We'll have to modify the runtime APIs for av-cores and the claim queue to advance all of the claims of the occupied cores by 1. (So that position 0 has the same meaning as now - what paraid can occupy the next slot). This is what I've been prototyping so far and it seems to work.

Another idea, which is more similar to how the claim queue currently works is to:
- right after processing the bitfields, collect the timed out and included cores.
- back new candidates
- advance the claim queue (by popping the front and pushing a new claim from the assigner to the back) on the cores where we backed new candidates (the newly occupied cores) or that are free. We only need to keep the old claim for an occupied core that wasn't yet freed.
This will also make sure that the claim queue always has the right length and does not change the semantics of the first item in the claim queue. I'll prototype this also and decide which looks better

**Comment by eskimor** [comment]
Hi @alindima ! Took me a while to understand what I meant back then myself, let me explain a bit better:

1. At the beginning of the block claim queue position 0 specifies what we would expect on the core if the core is either free or becomes free after bitfields. (This is equivalent to the end of the previous block, which is what nodes see)
2. We always advance the claim queue, except if an already occupied core stayed occupied. Note however, that claim queue position 0 already points to the item we are expecting (not the para that is currently occupying). This is also why point (1) is point (1) ... claim queue pos 0 already shows the expected entry, no claim queue processing necessary.

Claim queue position 0 _never_ points to the entry that is currently occupying the core, but always the next expected one.

Does this make sense?

**Comment by sandreim** [comment]
> 2. We always advance the claim queue, except if an already occupied core stayed occupied. Note however, that claim queue position 0 already points to the item we are expecting (not the para that is currently occupying). This is also why point (1) is point (1) ... claim queue pos 0 already shows the expected entry, no claim queue processing necessary.

This sounds problematic for RFC103 implementation. We don't enact and free the core until all of themthe chained candidates become available, but the claim queue will advance for some cores that the parachain has assigned in the future but not in top of the queue.

**Comment by alindima** [comment]
> Does this make sense?

Yes, that's pretty much what I meant with my "Another idea" above 😄

**Comment by eskimor** [comment]
@sandreim indeed, those timeouts are annoying. One observation: We only need (2c) for on-demand, we could cater to the needs of on-demand by adding another call to the interface:

```rust
fn advance_claim_queue_not_served(CoreIndex) -> Option<ParaId>;
```

Or similar. Indicating to the scheduler that the claim could not be served and thus the scheduler can push back the assignment back to the assignment provider, for it to be served at a later point in time.

This also makes the claim queue even cleaner, as it will just always progress, each and every block - thus keeping its predictions: They are either served or dropped, but never delayed.

**Comment by sandreim** [comment]
> @sandreim indeed, those timeouts are annoying. One observation: We only need (2c) for on-demand, we could cater to the needs of on-demand by adding another call to the interface:
> 
> ```rust
> fn advance_claim_queue_not_served(CoreIndex) -> Option<ParaId>;
> ```
> 
> Or similar. Indicating to the scheduler that the claim could not be served and thus the scheduler can push back the assignment back to the assignment provider, for it to be served at a later point in time.
> 
> This also makes the claim queue even cleaner, as it will just always progress, each and every block - thus keeping its predictions: They are either served or dropped, but never delayed.

Nice!  sounds good to me.
