### ISSUE TITLE
chain-spec-builder: Do not swallow unknown fields

### ISSUE THREAD

**Issue by skunert** [paritytech/polkadot-sdk#4873]
Follow up of https://github.com/paritytech/polkadot-sdk/pull/4685.

We should not swallow any fields when modifying existing chain-specs. Currently `para_id` and `relaychain` fields would not be present in the output chain spec.

**Comment by CrackTheCode016** [comment]
I believe the cause is due to the existing chain spec being parsed via `ChainSpec::from_json`, which assumes no extensions / custom fields, aka just the default config.

To ensure any fields can be preserved, we can simply parse the file via `fs::read`, then `serde_json::read_slice`, merge in place, versus converting to `ChainSpec`. Other option is to hardcode them as part of the default config but not sure we want that.
