### ISSUE TITLE
[Help] Mapping XCM Extrinsics Between Polkadot and Asset Hub

### ISSUE THREAD

**Issue by HmFlashy** [paritytech/polkadot-sdk#5433]
Issue Description:

I'm trying to efficiently map XCM Extrinsics between Polkadot and Asset Hub. My current approach involves listening to new blocks on both chains and filtering transactions based on involved addresses. However, I'm facing challenges in reliably determining if a transaction has been successfully completed on the destination chain.

Specific Questions:

XCM Message Data: Is there a way to extract relevant information from XCM messages on the destination chain to correlate it with the source chain transaction?
Transaction Status: How can I reliably determine if a transaction has been successfully completed on the Asset Hub? Are there specific events or status codes to look for?
Performance Optimization: Are there any techniques or best practices for optimizing the process of tracking and correlating XCM transactions across chains?

Additional Context:

I'm using Polkadot.js API for interacting with the Polkadot and Asset Hub networks.
I'm listening to new block events on both chains and filtering transactions based on involved addresses.
I'm trying to ensure that when I send DOT funds from Polkadot to Asset Hub, I can confidently track the transaction's status and completion.

**Comment by bkchr** [comment]
CC @paritytech/xcm

**Comment by acatangiu** [comment]
You can check how e.g. Subscan does it, their code is open-source, and they are tracking crosschain transfers: e.g. for Polkadot Relay: [dashboard](https://polkadot.subscan.io/xcm_dashboard), [messages](https://polkadot.subscan.io/xcm_message), [transfers](https://polkadot.subscan.io/xcm_transfer).

to your specific questions:

> XCM Message Data: Is there a way to extract relevant information from XCM messages on the destination chain to correlate it with the source chain transaction?

Yes, XCM messages have a `message_hash` associated with them that can be tracked crosschain.
E.g. [Transfer from AssetHub to Interlay](https://polkadot.subscan.io/xcm_message/polkadot-26bb094c1b48b39452a1de0c22baa5e16bbb950d):
- On AssetHub an `XcmpMessageSent` [event is emitted](https://assethub-polkadot.subscan.io/extrinsic/6959992-2?event=6959992-10) containing `0xd4d0fe831ea81353ed3956e959ad747d603f48aaa8a34c2bd518490b423f1a81` message hash.
- On Interlay an `xcmpqueue (Success)` [event is emitted](https://interlay.subscan.io/extrinsic/5958314-1?event=5958314-9) showing the same hash - this means the message executed properly, otherwise event would've been failure with a reason provided.

> Transaction Status: How can I reliably determine if a transaction has been successfully completed on the Asset Hub? Are there specific events or status codes to look for?

yes, all transactions emit (pallet-specific) events saying whether they succeeded or not (`outcome` is the result): [example event for pallet-xcm](https://assethub-polkadot.subscan.io/extrinsic/6959992-2?event=6959992-6).

> Performance Optimization: Are there any techniques or best practices for optimizing the process of tracking and correlating XCM transactions across chains?

I'm not aware of any better process other than following and correlating blocks and their events...

**Comment by HmFlashy** [comment]
Thanks a lot for your quick answer. But looking at this [example](https://bifrost.subscan.io/xcm_message/polkadot-b59122779bf56b71a4cc9a4cc393fce2be98e8a3), we can see the two extrinsics have been inserted in a block at the same time, so i am scared that I could miss some events on destination chain due to the fact it was too quick. Is there a way to compute the message id before hand ?

And the messageId could be not unique.

> yes, all transactions emit (pallet-specific) events saying whether they succeeded or not (outcome is the result): [example event for pallet-xcm](https://assethub-polkadot.subscan.io/extrinsic/6959992-2?event=6959992-6).

It looks like this event is only for the local xcm excecution, am I wrong ? https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/pallet-xcm/src/lib.rs#L1790-L1797

**Comment by HmFlashy** [comment]
And I agree Subscan is doing a great job at it but we don't have the same problem. They are tracking and indexing everything that is happening on chain. So it is a bit easier to map the extrinsics for them. But we don't want to index every xcm message going through each parachain just for this, we just want to get the information we need,
We need at some point to get the message id from the source chain and then catch the extrinsic with same messageId and same timestamp as the source chain extrinsic.

**Comment by HmFlashy** [comment]
I got one more little question. I found this XCM message. It failed on destination chain. How can we know what happened there ? I don't see any error log.
https://assethub-polkadot.subscan.io/xcm_message/polkadot-90a5fe60af6be9e0fc7a91a60756356d5b07fdb4

**Comment by acatangiu** [comment]
The on-chain runtime doesn't provide much information now on XCM failures, unfortunately. One more thing to work on to improve..

The de-facto way to debug these things right now is to use a debug runtime and replay the transaction using [chopsticks](https://github.com/AcalaNetwork/chopsticks).

E.g. for replaying your exact block (where error occurs) using a custom runtime:
```
npx @acala-network/chopsticks@latest run-block --endpoint=wss://polkadot-asset-hub-rpc.polkadot.io --block 6825655  --wasm-override=/path/to/runtimes/asset_hub_polkadot_runtime.wasm --runtime-log-level=5
```

**Comment by HmFlashy** [comment]
Thanks for your help much clearer now.
