### ISSUE TITLE
How to have custom messages for error in UI?

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/polkadot-sdk#5699]
Error messages are only one word, rather than a custom descriptive string. 
```rust
 // Errors inform users that something went wrong.
    #[pallet::error]
    pub enum Error<T> {
        /// Error names should be descriptive.
        NoneValue,
        /// Errors should have helpful documentation associated with them.
        StorageOverflow,
    }
```

Its become difficult to show custom messages in the frontend. What are the best practices of giving custom messages?

Something like [thiserror](https://docs.rs/thiserror/1.0.63/thiserror/) would have been better.

**Comment by bkchr** [comment]
In the front end you can match on these errors. The metadata also contains the documentation of your error message. Generally, I would not show any of these errors to a user as they are confusing.

@josepot and @carlosala happy to help you with this topic.

**Comment by josepot** [comment]
Exactly what @bkchr said!

In the metadata, the documentation comments above each variant of the `Error` enum provide more context about the errors. However, these comments are primarily intended for developers to understand the error's nature and not for displaying user-friendly messages on the frontend.

To handle custom error messages in your UI, the common approach is to map these errors to specific messages or actions based on the context of your application. For instance, if you're building a DApp with internationalization (i18n), you can map these error variants to different user-friendly messages in multiple languages. 

Here’s a basic workflow:
- Catch the error in your UI or middleware.
- Map the error (such as `NoneValue` or `StorageOverflow`) to a descriptive, user-friendly message based on the error type.
- Optionally, if your DApp has specific flows, you can perform a dry-run, catch the error, and take action like retrying with different parameters, rather than immediately showing the error to the user.

Ultimately, it's up to your DApp's logic and the UX you want to provide. You can create a higher-level layer that transforms these errors into meaningful interactions or messages in the frontend.

**Comment by amiyatulu** [comment]
ok. Thank you. Got it.
