### ISSUE TITLE
Coretime renewal price is wrong

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#6182]
The renew price suppose to be x% plus last purchase price, which is not happening currently on Polkadot coretime chain. All renews are 100DOT or more and their last purchase prices are well below that.

I think it is caused by this, which overrides the actual price https://github.com/paritytech/polkadot-sdk/blob/b4732add46910370443d092a3f479986060f6df5/substrate/frame/broker/src/tick_impls.rs#L219

**Comment by eskimor** [comment]
What do you mean their last purchase price? There was no last purchase price for any chain on Polkadot as of now. How it is supposed to work: https://grillapp.net/@eskimor/agile-coretime-renew-pricing-explained-182686?ref=12935

**Comment by xlc** [comment]
> There was no last purchase price for any chain on Polkadot as of now.

I don’t understand. This is the second sale and the renewal price for first sale is wrong.

**Comment by eskimor** [comment]
The renewal price is determined well ahead of time, as explained [here](https://grillapp.net/@eskimor/agile-coretime-renew-pricing-explained-182686?ref=12935).

**Comment by xlc** [comment]
Not sure if I misread or something. but can you explain how is 100 dot renewal price is calculated?

**Comment by eskimor** [comment]
It was set for initialization for the first sale as the first sale has no previous sale to base this number on. All further sales will use the actual sellout price of the previous sale for lease renewal price.

Calculation is roughly based on [this](https://forum.polkadot.network/t/initial-coretime-pricing/5187/7).

**Comment by xlc** [comment]
can you walk the numbers with me please? I just want to know how is 100 DOT calculated.

<img width="858" alt="Screenshot 2024-10-24 at 11 09 12 PM" src="https://github.com/user-attachments/assets/2c1afb3e-e103-41b9-a6d3-4d9e41c52468">

core 52 is sold 52.86 DOT

<img width="767" alt="Screenshot 2024-10-24 at 11 09 55 PM" src="https://github.com/user-attachments/assets/b7d104ff-094f-469f-aaf7-9c7a545d6a7d">

but the renewal price is 103 DOT

the renewal bump is 3%

<img width="249" alt="Screenshot 2024-10-24 at 11 11 37 PM" src="https://github.com/user-attachments/assets/3ba705e0-b38e-4281-acb5-de630003f41b">

can you point me out which line of code is writing 103 DOT to the stroage and how is the 103 DOT calculated? what are the inputs and which function does the math?

**Comment by eskimor** [comment]
That's indeed weird, but I just figured out what is going on. As in your screenshot, you can see that they bought core 52, but they renewed core 60: https://coretime-polkadot.subscan.io/extrinsic/329458-2

So the renew status is for a different core. Aventus is currently owning two cores: 

- 52, the one they purchased, but as far as I can see never assigned. It only has no renewal rights.
- 60, the core we granted them in the migration fixing the lease lengths [here](https://github.com/polkadot-fellows/runtimes/blob/afc36ca73146d7e22887fb11c6631a7129d68dd2/system-parachains/coretime/coretime-polkadot/src/migrations.rs#L233).

This is why you see an renewal entry with the previous renewal (100) bumped.

**Comment by SBalaguer** [comment]
@xlc I think that the issue here is that we are talking about the same core, but at different moments in time. When a task renews it's core, it's assigned a completely new core, they don't hold the same that in the previous cycle. 
So in this case we have:
- [Core 52 was sold](https://coretime-polkadot.subscan.io/coretime/287565-5040-52-1208925819614629174706175) on [Cycle1](https://coretime-polkadot.subscan.io/coretime_sale/1) for 52.86 DOT. Once assigned, this core can then be renewed, and renewing it would cost 3% more.
- Core 60 (Aventus, task 2056) was renewed on Cycle2 for 100 DOT (based on the initial pricing @eskimor shared before). [This renewal](https://coretime-polkadot.subscan.io/block/329458?tab=event&event=329458-6) resulted in the fact that task 2056 will be assigned core 52 in the upcoming cycle (Cycle3).
- Renewing core 52 on Cycle3 will be 103 DOT, which is +3% vs what task 2056 paid to renew core 60. This is what you are seeing today on regionX. That's why it says that the core is valid for 7w, which is the remaining of this cycle, plus the following one.

![image](https://github.com/user-attachments/assets/bd52a3c9-c251-46f9-b521-017b83bfcd3e)

In the end what's confusing is that renewing a core assigns you to another core for the upcoming cycle, you don't maintain the previous one. So core 52 on Cycle1 has nothing to do with core 52 on Cycle3. The only exception is for leases that always maintain their core.

**Comment by xlc** [comment]
Thanks for the explanation. I guess the UI need to find some ways to make this bit more obvious.
