### ISSUE TITLE
Fix zombienet test `zombienet-parachain-template-smoke`

### ISSUE THREAD

**Issue by pepoviola** [paritytech/polkadot-sdk#6575]
Fails from yesterday

https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792663
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792597
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792532
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792398
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792333
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792267
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792202
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792134
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792065
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7792000
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791935
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791873
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791812
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791746
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791616
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791555
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791490
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791490
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791424
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791359
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791294
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791229
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791163
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791090
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7791021
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7790917
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7790844
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7790622
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7790554
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7790489
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7790341
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7789956
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7789895
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7789700
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7789633
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7789365
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7789018
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788957
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788890
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788824
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788759
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788629
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788563
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788360
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788293
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788222
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7788156
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787879
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787809
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787744
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787611
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787545
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787478
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7787411
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786980
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786915
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786849
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786783
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786717
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786651
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786589
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786523
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786462
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786401
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7786340

cc: @iulianbarbu

**Comment by iulianbarbu** [comment]
I think the issue comes from the fact that zombienet calls the `minimal-template-node build-spec` command and the result is a dev-plain.json which contains some `aura` related configs, although this shouldn't be the case considering `minimal-template-node` doesn't have a runtime configured with AURA. Not sure how the aura config makes its way to minimal chain spec.

Looking now into finding the precise commands that run and make up towards this chain spec.

**Comment by iulianbarbu** [comment]
1. I think the issue comes from this function:  https://github.com/paritytech/zombienet-sdk/blob/main/crates/orchestrator/src/generators/chain_spec.rs#L508. It does this check here: https://github.com/paritytech/zombienet-sdk/blob/main/crates/orchestrator/src/generators/chain_spec.rs#L569, but it will go on the `else` branch: https://github.com/paritytech/zombienet-sdk/blob/main/crates/orchestrator/src/generators/chain_spec.rs#L579, which sets up AURA and GRANDPA authorities by default.

2. How this fails is that the `minimal_template_block_production_test` calls: https://github.com/paritytech/zombienet-sdk/blob/v0.2.15/crates/orchestrator/src/lib.rs#L91, which calls https://github.com/paritytech/zombienet-sdk/blob/v0.2.15/crates/orchestrator/src/lib.rs#L129 (which generates a correct chain_spec). After that we call the function from point 1. (https://github.com/paritytech/zombienet-sdk/blob/v0.2.15/crates/orchestrator/src/lib.rs#L168), which modifies the previously generated plain chain spec, and after this function call, we call into https://github.com/paritytech/zombienet-sdk/blob/v0.2.15/crates/orchestrator/src/lib.rs#L180, which calls `build-spec` again but with an additional `--raw` flag and using the previously modified plain `chain_spec`, which fails with the error we saw in the failed jobs logs from the issue description.

We must release a fix where we don't assume relaychain chain specs would always want `aura` and `grandpa` authorities. I think this commit: https://github.com/paritytech/zombienet-sdk/commit/cae47b2ec51193087ebc6d300cb6b2ac220846d5 introduced the behavior which results in failing jobs. @pepoviola any idea how to fix it?

**Comment by pepoviola** [comment]
Nice catch @iulianbarbu! we should only override those `iff` there are present. I will fix this and draft a new version (and then update it here). Thanks again for checking this.

**Comment by rockbmb** [comment]
Thanks @iulianbarbu and @pepoviola.

I've been curious about the Zombienet failures in CI, and also wanted to know why they occur.
