### ISSUE TITLE
Why does Grandpa not use sr25519?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot-sdk#6819]
Originally from SE: https://substrate.stackexchange.com/questions/10629/why-does-grandpa-not-use-sr25519

It's quite interesting, and I cannot find any documentation for this.

**Comment by bkchr** [comment]
CC @burdges

**Comment by burdges** [comment]
HSM support already exists for ed25519.  That's the big reason.  Also more implementations, etc.

We know only a few downsides to ed25519:

The group not being prime order means additional functionality could easily be implemented wrong.  Everstake and Cardano screwed up soft derivations.  Monero made worse mistakes repeatedly.  And many more.  Ristretto fixes this, so sr25519 was meant to protect our ecosystem from such mistakes, but so far we've not delved too much into altered signing tools, since we do everything on-chain mostly.

That's about it really, but other reasons for not using ed25519:
- ed25519 is not post-quantum.
- If you can rotate keys lots, then Rabin-Williams signatures (RSA-like) have faster verifiers: https://cr.yp.to/sigs/rwsota-20080131.pdf https://iacr.org/archive/eurocrypt2008/49650070/49650070.pdf  https://crypto.stackexchange.com/questions/26223/why-isnt-rabin-williams-cryptosystem-widely-used
- You could prefer a specific base field or group order for some reason, like usage inside a SNARK, or FFTs, or in a cycle of curves, or whatever.  
- You could prefer a different hash function for some reason, like usage inside a SNARK, but this comes up less.  sr25519 again selected merlin to minimize ecosystem mistakes when hashing.

Also, arguably sr25519 made these safer choices prematurely:

Arguably, "transcript" hashing is overkill here, and arguably later "transcript" designs make more sense than merlin:  My ark-transcript plays much nicer with IEEE standards and rust's std.  SAFE API is slightly more efficent, which benefits usage inside a SNARK.

Arguably, Ristretto should've been designed to expose maps to ed25519, by fixing one of the two branches of the square root.  Afaik nobody ever properly justified not exposing the map between Ristretto and ed25519.  It'd require test vectors for the mapping, maybe ignored by some Ristretto only implementation.  Yet, if said implementation could fix its branch of the square root when later exposing the mapping, making this argument unjustified.

Importantly, HdV and Isis hate DJB over Appelbaum, so maybe they disliked Ristretto feeling dependent upon ed25519.  If Ristretto exposed this mapping, then we'd probably all be using some ed25519 variant which encodes points using Ristretto, so maybe they disliked improving ed25519 too.  

Red25519 is a variant of ed25519 by Zcash, which further specifies ed25519 itself, without using isogenies like Ristretto does.  It doesn't really give the "ecosystem safety" but it helps.

**Comment by AurevoirXavier** [comment]
> I'm happy to copy this answer to substrate.SE if you copy the question there.

There is already a question there. Please.
