### ISSUE TITLE
Accept/Support Custom Header Hasher from Parachain

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot-sdk#6992]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Some parachains use their own Hash type.

For instance, [Hyperbridge](https://github.com/polytope-labs/hyperbridge/blob/a2cb646d3aee28e04755c704bba1cf7a3672b333/parachain/runtimes/nexus/src/lib.rs#L121) defines a custom hash implementation (`keccak256`).

I discovered this while trying to match a Hyperbridge block with the Polkadot event’s `parainclusion::CandidateIncluded.para_head` field. Unfortunately, all the hash values were mismatched, making it impossible to index the Hyperbridge block based on the `para_head` value.

It seems that Polkadot assumes the use of `blake2_256` for generating hashes, which may not align with Hyperbridge’s implementation.

Might relate to #5224?

**Comment by bkchr** [comment]
`parainclusion::CandidateIncluded.para_head` this is a field of a relay chain structure. That right now the hash matches most of the parachain header hashes is a coincidence, not done this way by design. There could be other chains which may insert different data to the head or just store a hash in para head. All of that is possible. These `para_head` hash is required by the internals of the relay chain and can not be changed.

For your request, the best is that you directly fetch all the heads and match them to the parachains. The `paras::Heads` will give you directly the mapping from `ParaId` to `Head`.

**Comment by AurevoirXavier** [comment]
> That right now the hash matches most of the parachain header hashes is a coincidence, not done this way by design.

Make sense.
