### ISSUE TITLE
Fix spurious runtime not supported errors

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#793]
A couple of times we get messages on versi that certain runtime requests are not supported. Which is not expected, as the deployed runtime does support them:

```


2022-08-16 14:46:09 | 2022-08-16 12:46:09.709  WARN tokio-runtime-worker parachain::dispute-coordinator: error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "candidate_events" }))
-- | --
  |  

```

Full logs: https://grafana.parity-mgmt.parity.io/goto/7HD0ZPm4k?orgId=1

This should be investigated as working runtime calls are crucial for disputes to work correctly. Related issue paritytech/polkadot#5882 

TODOs:

- [x] Have https://github.com/paritytech/substrate/pull/12707 merged in substrate.
- [x] Show better error message instead of the misleading `parachain::dispute-coordinator: error=Runtime(RuntimeRequest(NotSupported))` https://github.com/paritytech/polkadot/pull/6288

**Comment by tdimitrov** [comment]
I think we are quite familiar with the root cause for this issue and we can close it.

To summarise the problem. Each runtime call performed via runtime api subsystem consists of two calls:
1. ApiVersion call to determine the runtime version and if the desired runtime call is supported.
2. The desired runtime call.

The error occurs at step 1. For example (actual occurrence on versi):
```
WARN tokio-runtime-worker parachain::runtime-api: cannot query the runtime API version: Api called for an unknown Block: State already discarded for 0xf733059cf939d9c753f29b2a5d7cca05c334d9ced1151445f651702fe52f4d0a
```
Digging further what happened with the relay parent explains the error:
```
 WARN tokio-runtime-worker sync: 💔 Ignored block (#224794 -- 0xf733…4d0a) announcement from 12D3KooWD4RtZaY97mncXTFcerDmzuQBpeJjDmpUtEQLcFRLeJsw because all validation slots for this peer are occupied.
 ```
 
# Steps to investigate such issues
Usually this is what I do (based on the example I mentioned above):
1. You see a state discarded error. Or you look for it explicitly with something like `{level="WARN",subtarget="runtime-api"} |~ "State discarded`.
2. Pinpoint a single node for debugging and check the errors there - `{level="WARN",subtarget="runtime-api", node="versi-validator-a-node-10"}`
3. Zoom in around a single warn occurrence and investigate for ERROR/WARN messages. Explicitly look for `{level=WARN, subtarget="runtime=api"} |~ "cannot query the runtime API version"`. Then you can find a reason for the failure. E.g.:
```
WARN tokio-runtime-worker parachain::runtime-api: cannot query the runtime API version: Runtime code error: `:code` hash not found
```
This step wasn't very useful for the example I was debugging so move on to the next step.
4. If WARN/ERROR messages around the initial warning doesn't help try searching for the block with `{node="versi-validator-a-node-10"} |~ "0xf733.*0a" !~ "State already discarded for"`. For this particular case I saw:
```
 WARN tokio-runtime-worker sync: 💔 Ignored block (#224794 -- 0xf733…4d0a) announcement from 12D3KooWCN4kP7zoA5Bg2KGvvtNnTMi7qot9H4kG6RL1bh8Fq6wx because all validation slots for this peer are occupied. 
```
