### ISSUE TITLE
Update `teleport_assets` Extrinsics for Foreign Assets

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot-sdk#96]
Right now the `teleport_assets_*` extrinsics use the teleported asset to `BuyExecution` on the destination chain. This can cause a problem if the teleported asset cannot be used for fee payment.

As an example, a parachain may be a trusted teleporter of its own native asset, but not for DOT, which is valid for fee payment on Asset Hub.

The extrinsic should be able to construct alternate XCM programs that would pay fees according to the parameters. Options include:

1. `WithdrawAsset` from the parachain's sovereign account on the destination chain and use that for `BuyExecution`.
2. Allow the deposit of reserve assets (e.g. DOT) prior to the `ReceiveTeleportedAsset` instruction.

Probably requires changes to the impl of `XcmExecutor` (e.g. in [`InitiateTeleportedAsset`](https://github.com/paritytech/polkadot/blob/247e4a7/xcm/xcm-executor/src/lib.rs#L667).

_Originally posted by @joepetrowski in https://github.com/paritytech/cumulus/pull/2935#discussion_r1280240817_

**Comment by joepetrowski** [comment]
@acatangiu is this addressed by some of the other `transfer` changes you've made recently? Or should we leave it open?

**Comment by acatangiu** [comment]
This is possible now, but **only if the Parachain trusts AH as reserve for DOT**, so it can send `AssetA` **and** `DOT` directly to it (in same XCM message):

```
ParaA --Assets--> AH
```
where
```
Assets = [AssetA (teleport), DOT (reserve-withdraw)]
```
fees paid with DOT

----

If the Parachain does NOT trust AH as reserve, there is NO way to send both assets _at once_ (in a single transfer), because they would have different routes, so two independent asynchronous messages with no ordering guarantee:

```
ParaA --------AssetA--------> AH
   |                           ^
   |                           |
   +--DOT--> Relaychain --DOT--+
```

if the transfer is fired for both assets at the same time, `AssetA` can arrive before the `DOT` and there is no way to control the order, so DOT cannot be used to pay for fees.

----

## When Parachain trusts AH as reserve for DOT

Simply use `pallet_xcm::transfer_assets()` and it will do the rest.

Example: [bidirectional transfers of `[ForeignAsset, DOT]` between Penpal and AH](https://github.com/paritytech/polkadot-sdk/blob/909bfc2d7c00a0fed7a5fd4e5292aa3fbe2299b6/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs#L662C1-L670C2), using [pallet_xcm::transfer_assets()](https://github.com/paritytech/polkadot-sdk/blob/909bfc2d7c00a0fed7a5fd4e5292aa3fbe2299b6/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/teleport.rs#L257C1-L266C2).

Or one can also _explicitly_ define the "route" and "types" of transfer used with `pallet_xcm::transfer_assets_using_type_and_then()`.

Example: [bidirectional transfers of `[ForeignAsset, DOT]` between Penpal and AH](https://github.com/paritytech/polkadot-sdk/blob/909bfc2d7c00a0fed7a5fd4e5292aa3fbe2299b6/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs#L638C1-L649C2), using [pallet_xcm::transfer_assets_using_type_and_then()](https://github.com/paritytech/polkadot-sdk/blob/909bfc2d7c00a0fed7a5fd4e5292aa3fbe2299b6/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs#L112C1-L129C2).
